#pragma once

#include "net/minecraft/client/ui/scene/scenes/UIScene_AchievementsMenu.h"
#include "net/minecraft/core/profile/C_4JProfile.h"

wchar_t* GetRichPresenceStringFromId(int id);

class CProfile : public C_4JProfile {
public:
    static CProfile* sInstance;

    CProfile();

    void Initialise(const void*, const void*, unsigned short, unsigned int, unsigned int, unsigned int*, int,
                    unsigned int*) override;
    int GetLockedProfile() override;
    void
    SetLockedProfile(int) override;  // guessing int here is flags provided by the OS when getting the user
    bool IsSignedIn(int) override;
    bool IsSignedInLive(int) override;
    bool IsSigningIn(int) override;
    bool IsGuest(int) override;
    void sub_710079238C() override;        // Wii U says CProfile::RequestSignInUI
    void SignInUser(void*, int) override;  // void * used to be MiiDataEntry
    void sub_710079239C() override;
    void sub_71007923AC() override;
    void sub_71007923C0() override;
    void sub_71007923F0() override;
    void sub_7100792640() override;
    void sub_710079188C() override;
    void sub_7100791B48() override;
    void sub_7100791B78() override;
    void sub_7100792734() override;
    void sub_71007926EC() override;
    void sub_7100792BE8() override;
    void sub_7100791DB0() override;
    void sub_7100791F5C() override;
    void sub_7100791FFC() override;
    void sub_710079201C() override;
    void sub_7100792750() override;
    void sub_7100792028() override;
    void sub_7100792184() override;
    void sub_7100792754() override;
    void sub_71007927BC() override;
    void sub_7100791ECC() override;
    void sub_7100791ED4() override;
    void sub_7100791EDC() override;
    int GetPrimaryPad() override;
    void sub_7100794A3C() override;
    void sub_7100794A78() override;
    void sub_7100792A30() override;
    void sub_7100792A54() override;
    void sub_7100792AAC() override;
    void sub_7100792BFC() override;
    void sub_7100792C04() override;
    void sub_7100792C0C() override;
    bool IsFullVersion() override;
    void SetFullVersion(bool v) override;
    void SetSignInChangeCallback(void (*)(void*, bool, unsigned int), void*) override;
    void sub_7100792C1C() override;
    void sub_7100794A20() override;
    void sub_7100794A2C() override;
    void sub_7100794A34() override;
    void sub_7100794B58() override;
    void sub_7100794B50() override;
    void SetProfileReadErrorCallback(void (*)(void*), void*) override;
    void sub_710079235C() override;
    void Tick() override;
    void AwardManagerOnCreate() override;
    void RegisterAward(int idx, int idx2, eAwardType type, int name, int desc) override;
    void sub_71007A2DE4() override;
    void sub_71007A2DEC() override;
    void sub_71007A2DF4() override;
    void sub_71007A2894() override;
    void sub_71007A2994() override;
    void SetOnAwardHandler(void (*)(), void*) override;
    void sub_7100792C4C() override;
    void RichPresenceRegisterPresenceString(int, int) override;
    void RichPresenceRegisterContext(int, int) override;
    void RichPresenceRegisterContextString(int, int, int) override;
    void RichPresenceInit(int, int) override;
    void sub_7100793CE0() override;
    void sub_7100794404() override;
    void sub_71007946A8() override;
    void sub_71007946B0() override;
    void sub_7100794804() override;
    void SetRichPresenceGetStringCallback(wchar_t* (*)(int)) override;
    void sub_7100792C38() override;
    void sub_710079457C() override;
    void sub_710079493C() override;
    void SetUpsellCallback(void (*)(void*, eUpsellType, eUpsellResponse, int), void*) override;
    void sub_7100794B6C() override;
    void sub_71007929E4() override;
    void sub_7100792A08() override;
    void sub_7100792A24() override;
    void sub_7100792BF4() override;
    void sub_7100792AF0() override;
    void sub_7100792AF4() override;
    void sub_7100792BE0() override;
    void sub_7100792B80() override;
    void sub_7100792B7C() override;
    void sub_7100792B74() override;
    void sub_7100792B88() override;
    void sub_7100792BC8() override;
    void sub_7100792BD0() override;
    void sub_7100792BD8() override;
    void SetSignInChoicesCallback(int (*)(int)) override;
    void sub_7100792C44() override;
    void sub_7100791DAC() override;
    void sub_7100791D54() override;
    // virtuals are completly different than WiiU, this class is completly different

    /*void GetLockedProfile() override;
    void SetLockedProfile(int) override;
    void IsSignedIn(int) override;
    void IsSignedInLive(int) override;
    void IsSigningIn(int) override;
    void IsGuest(int) override;
    void RequestSignInUI(bool,bool,bool,bool,bool,int (*)(void *,bool,int,bool),void *,int) override;
    void SignInUser(MiiDataEntry *,int) override;
    void SignOutUser(FFLCreateID &) override;
    void SignOutUser(int) override;
    void SetUserSigningIn(int,bool) override;
    void DisplayOfflineProfile(int (*)(void *,bool,int),void *,int) override;
    void sub_32F9A00() override;
    void SetPrimaryPlayerChanged(bool) override;
    void QuerySigninStatus() override;
    void GetXUID(int,PlayerUID *,bool) override;
    void sub_32F9D8C() override;
    void AllowedToPlayMultiplayer(int) override;
    void StartTrialGame() override;
    void sub_32F9DB8() override;
    void CanViewPlayerCreatedContent(int,bool,PlayerUID *,unsigned int) override;
    void GetProfileAvatar(int,int (*)(void *,unsigned char *,unsigned int),void *) override;
    void CancelProfileAvatarRequest() override;
    void SetGetStringFunc(wchar_t const *(*)(int)) override;
    void SetPlayerListTitleID(int) override;
    void SetFatalTrophyErrorID(int) override;
    void GetPrimaryPad() override;
    void SetPrimaryPad(int) override;
    void ClearGameUsers() override;
    void GetMiiName(int) override;
    void GetGamertag(int) override;
    void GetDisplayName(int) override;
    void GetNetworkAccountID() override;
    void IsFullVersion() override;
    void SetFullVersion(bool) override;
    void SetSignInChangeCallback(void (*)(void *,bool,unsigned int),void *) override;
    void sub_32FB28C() override;
    void sub_32FE5C8() override;
    void RegionIsNorthAmerica() override;
    void LocaleIsUSorCanada() override;
    void GetLiveConnectionStatus() override;
    void IsSystemUIDisplayed() override;
    void SetProfileReadErrorCallback(void (*)(void *),void *) override;
    void ResetProfileProcessState() override;
    void Tick() override;
    void sub_3313960() override;
    void GetAwardId(int) override;
    void GetAwardType(int) override;
    void sub_3313988() override;
    void sub_33143A8() override;
    void sub_331455C() override;
    void sub_3314610() override;
    void Terminate() override;
    void sub_32FC18C() override;
    void sub_32FC1D4() override;
    void RichPresenceRegisterContextString(int,int,int) override;
    void RichPresenceInit(int,int) override;
    void sub_32FE04C() override;
    void sub_32FE0E4() override;
    void SetRichPresenceSettingFn(int (*)(void const *)) override;
    void SetRichPresenceGameModeData(nn::fp::GameMode &) override;
    void SetFriendPresenceChangeCallback(void (*)(unsigned int,void *),void *) override;
    void SetRichPresenceGetStringCallback(wchar_t *(*)(int)) override;
    void SetFriendPresenceOnline(bool) override;
    void sub_32FE60C() override;
    void SetUpsellCallback(void (*)(void *,eUpsellType,eUpsellResponse,int),void *) override;
    void SetDebugFullOverride(bool) override;
    void SetNetworkStatus(bool) override;
    void SetNetworkStatusWithoutSigninChange(bool) override;
    void TryToConnectOnline() override;
    void GetSignedInUsersMask() override;
    void RefreshChatAndContentRestrictions(void (*)(void *),void *) override;
    void sub_32FB908() override;
    void SetServiceID(char *) override;
    void HandleNetworkTicket(int,void *) override;
    void SetMinimumAge(int) override;
    void getUserID(int) override;
    void getQuadrant(ACTUuid &) override;
    void SetSignInChoicesCallback(int (*)(int)) override;
    void GetSignInEntries() override;
    void LoadAllMiiData() override;
    void FreeAllMiiData() override;
    void GetNumSysUserMiis() override;
    void GetNumFavouriteMiis() override;
    void GetNumGuestMiis() override;
    void GetSysUserMiiData(int) override;
    void GetFavouriteMiiData(int) override;
    void GetGuestMiiData(int) override;
    void IsHasAchievementsFile(int) override;*/
    char m_gap8[40];
    void* m_qword30;
    char m_gap38[216];
    char m_char110;
    char m_gap111[1583];
    int m_dword740;
    int m_dword744;
    int m_dword748;
    int m_dword74C;
    void* m_qword750;
    void* m_qword758;
    void* m_qword760;
    void* m_qword768;
    char m_gap770[16];
    char m_byte780;
    __attribute__((aligned(2))) char m_byte782;
    int m_dword784;
    int m_dword788;
    int m_dword78C;
    int m_dword790;
    uint16_t m_word794;
    uint16_t m_word796;
    char m_byte798;
    char m_gap799[2];
    char m_byte79B;
    void* m_qword7A0;
    void* m_qword7A8;
    void* m_qword7B0;
    int m_dword7B8;
    char m_gap7Bc[12];
    int (*m_signInChoicesCallback)(int);
    int m_gap7D0[3];
    char m_byte7Dc;
    void* m_qword7E0;
    char m_gap7E8[20];
    int m_dword7Fc;
    int m_dword800;
    void* m_qword808;
    int m_dword810;
    void* m_qword818;
    char m_gap820[20];
    uint16_t m_word834;
    uint16_t m_word836;
    uint16_t m_word838;
    uint16_t m_word83A;
    int m_dword83C;
    void* m_qword840;
    int m_dword848;
    void* m_qword850;
    int m_dword858;
    char m_byte85C;
    bool m_isInitalised;
    char m_gap85E;
    char m_byte85F;
    char m_byte860;
    char m_gap861[39];
    char m_byte888;
    char m_gap889[39];
    void* m_qword8B0;
    void* m_qword8B8;
    void* m_qword8C0;
    void* m_qword8C8;
    void* m_qword8D0;
    void* m_qword8D8;
    void* m_qword8E0;
    void* m_qword8E8;
    void* m_qword8F0;
    char m_gap8F8[152];
    std::unordered_map<int, int> m_ap990;
    std::unordered_map<int, int> m_ap9B8;
    std::unordered_map<int, std::unordered_map<int, int>> m_ap9E0;
    char m_gapA04[76];
    void* m_qwordA50;
    void* m_qwordA58;
    void* m_qwordA60;
    void* m_qwordA68;
    void* m_qwordA70;
    void* m_qwordA78;
    void* m_qwordA80;
    void* m_qwordA88;
    void* m_qwordA90;
    void* m_qwordA98;
    void* m_qwordAA0;
    void* m_qwordAA8;
    char m_gapAB0[70];
    std::unordered_map<int, int> m_apAF8;
    std::unordered_map<int, int> m_apB20;
    std::unordered_map<int, int> m_apB48;
    std::unordered_map<int, int> m_apB70;
    char m_gapB98[32];  // another map?
    void (*m_onAwardHandler)();
    void* m_awardHandlerVar;
    void* m_qwordBD0;
    void* m_qwordBD8;
    void* m_qwordBE0;
    void* m_qwordBE8;
    int m_dwordBF0;
    char m_gapBF4[1580];
    void* m_qword1220;
    void* m_qword1228;
    void* m_qword1230;
    void* m_qword1238;
    void* m_qword1240;
    void* m_qword1248;
    char m_gap1250[30];
};
