#pragma once

#include "net/minecraft/client/ui/scene/scenes/UIScene_AchievementsMenu.h"
#include "net/minecraft/core/profile/C_4JProfile.h"

wchar_t* GetRichPresenceStringFromId(int id);

class CProfile : public C_4JProfile {
public:
    static CProfile* sInstance;

    CProfile();

    void Initialise(const void*, const void*, unsigned short, unsigned int, unsigned int, unsigned int*, int,
                    unsigned int*) override;
    int GetLockedProfile() override;
    void
    SetLockedProfile(int) override;  // guessing int here is flags provided by the OS when getting the user
    bool IsSignedIn(int) override;
    bool IsSignedInLive(int) override;
    bool IsSigningIn(int) override;
    bool IsGuest(int) override;
    void sub_710079238C() override;        // Wii U says CProfile::RequestSignInUI
    void SignInUser(void*, int) override;  // void * used to be MiiDataEntry
    void sub_710079239C() override;
    void sub_71007923AC() override;
    void sub_71007923C0() override;
    void sub_71007923F0() override;
    void sub_7100792640() override;
    void sub_710079188C() override;
    void sub_7100791B48() override;
    void sub_7100791B78() override;
    void sub_7100792734() override;
    void sub_71007926EC() override;
    void sub_7100792BE8() override;
    void sub_7100791DB0() override;
    void sub_7100791F5C() override;
    void sub_7100791FFC() override;
    void sub_710079201C() override;
    void sub_7100792750() override;
    void sub_7100792028() override;
    void sub_7100792184() override;
    void sub_7100792754() override;
    void sub_71007927BC() override;
    void sub_7100791ECC() override;
    void sub_7100791ED4() override;
    void sub_7100791EDC() override;
    int GetPrimaryPad() override;
    void sub_7100794A3C() override;
    void sub_7100794A78() override;
    void sub_7100792A30() override;
    void sub_7100792A54() override;
    void sub_7100792AAC() override;
    void sub_7100792BFC() override;
    void sub_7100792C04() override;
    void sub_7100792C0C() override;
    bool IsFullVersion() override;
    void SetFullVersion(bool v) override;
    void SetSignInChangeCallback(void (*)(void*, bool, unsigned int), void*) override;
    void sub_7100792C1C() override;
    void sub_7100794A20() override;
    void sub_7100794A2C() override;
    void sub_7100794A34() override;
    void sub_7100794B58() override;
    void sub_7100794B50() override;
    void SetProfileReadErrorCallback(void (*)(void*), void*) override;
    void sub_710079235C() override;
    void Tick() override;
    void AwardManagerOnCreate() override;
    void RegisterAward(int idx, int idx2, eAwardType type, int name, int desc) override;
    void sub_71007A2DE4() override;
    void sub_71007A2DEC() override;
    void sub_71007A2DF4() override;
    void sub_71007A2894() override;
    void sub_71007A2994() override;
    void SetOnAwardHandler(void (*)(), void*) override;
    void sub_7100792C4C() override;
    void RichPresenceRegisterPresenceString(int, int) override;
    void RichPresenceRegisterContext(int, int) override;
    void RichPresenceRegisterContextString(int, int, int) override;
    void RichPresenceInit(int, int) override;
    void sub_7100793CE0() override;
    void sub_7100794404() override;
    void sub_71007946A8() override;
    void sub_71007946B0() override;
    void sub_7100794804() override;
    void SetRichPresenceGetStringCallback(wchar_t* (*)(int)) override;
    void sub_7100792C38() override;
    void sub_710079457C() override;
    void sub_710079493C() override;
    void SetUpsellCallback(void (*)(void*, eUpsellType, eUpsellResponse, int), void*) override;
    void sub_7100794B6C() override;
    void sub_71007929E4() override;
    void sub_7100792A08() override;
    void sub_7100792A24() override;
    void sub_7100792BF4() override;
    void sub_7100792AF0() override;
    void sub_7100792AF4() override;
    void sub_7100792BE0() override;
    void sub_7100792B80() override;
    void sub_7100792B7C() override;
    void sub_7100792B74() override;
    void sub_7100792B88() override;
    void sub_7100792BC8() override;
    void sub_7100792BD0() override;
    void sub_7100792BD8() override;
    void SetSignInChoicesCallback(int (*)(int)) override;
    void sub_7100792C44() override;
    void sub_7100791DAC() override;
    void sub_7100791D54() override;
    // virtuals are completly different than WiiU, this class is completly different

    /*void GetLockedProfile() override;
    void SetLockedProfile(int) override;
    void IsSignedIn(int) override;
    void IsSignedInLive(int) override;
    void IsSigningIn(int) override;
    void IsGuest(int) override;
    void RequestSignInUI(bool,bool,bool,bool,bool,int (*)(void *,bool,int,bool),void *,int) override;
    void SignInUser(MiiDataEntry *,int) override;
    void SignOutUser(FFLCreateID &) override;
    void SignOutUser(int) override;
    void SetUserSigningIn(int,bool) override;
    void DisplayOfflineProfile(int (*)(void *,bool,int),void *,int) override;
    void sub_32F9A00() override;
    void SetPrimaryPlayerChanged(bool) override;
    void QuerySigninStatus() override;
    void GetXUID(int,PlayerUID *,bool) override;
    void sub_32F9D8C() override;
    void AllowedToPlayMultiplayer(int) override;
    void StartTrialGame() override;
    void sub_32F9DB8() override;
    void CanViewPlayerCreatedContent(int,bool,PlayerUID *,unsigned int) override;
    void GetProfileAvatar(int,int (*)(void *,unsigned char *,unsigned int),void *) override;
    void CancelProfileAvatarRequest() override;
    void SetGetStringFunc(wchar_t const *(*)(int)) override;
    void SetPlayerListTitleID(int) override;
    void SetFatalTrophyErrorID(int) override;
    void GetPrimaryPad() override;
    void SetPrimaryPad(int) override;
    void ClearGameUsers() override;
    void GetMiiName(int) override;
    void GetGamertag(int) override;
    void GetDisplayName(int) override;
    void GetNetworkAccountID() override;
    void IsFullVersion() override;
    void SetFullVersion(bool) override;
    void SetSignInChangeCallback(void (*)(void *,bool,unsigned int),void *) override;
    void sub_32FB28C() override;
    void sub_32FE5C8() override;
    void RegionIsNorthAmerica() override;
    void LocaleIsUSorCanada() override;
    void GetLiveConnectionStatus() override;
    void IsSystemUIDisplayed() override;
    void SetProfileReadErrorCallback(void (*)(void *),void *) override;
    void ResetProfileProcessState() override;
    void Tick() override;
    void sub_3313960() override;
    void GetAwardId(int) override;
    void GetAwardType(int) override;
    void sub_3313988() override;
    void sub_33143A8() override;
    void sub_331455C() override;
    void sub_3314610() override;
    void Terminate() override;
    void sub_32FC18C() override;
    void sub_32FC1D4() override;
    void RichPresenceRegisterContextString(int,int,int) override;
    void RichPresenceInit(int,int) override;
    void sub_32FE04C() override;
    void sub_32FE0E4() override;
    void SetRichPresenceSettingFn(int (*)(void const *)) override;
    void SetRichPresenceGameModeData(nn::fp::GameMode &) override;
    void SetFriendPresenceChangeCallback(void (*)(unsigned int,void *),void *) override;
    void SetRichPresenceGetStringCallback(wchar_t *(*)(int)) override;
    void SetFriendPresenceOnline(bool) override;
    void sub_32FE60C() override;
    void SetUpsellCallback(void (*)(void *,eUpsellType,eUpsellResponse,int),void *) override;
    void SetDebugFullOverride(bool) override;
    void SetNetworkStatus(bool) override;
    void SetNetworkStatusWithoutSigninChange(bool) override;
    void TryToConnectOnline() override;
    void GetSignedInUsersMask() override;
    void RefreshChatAndContentRestrictions(void (*)(void *),void *) override;
    void sub_32FB908() override;
    void SetServiceID(char *) override;
    void HandleNetworkTicket(int,void *) override;
    void SetMinimumAge(int) override;
    void getUserID(int) override;
    void getQuadrant(ACTUuid &) override;
    void SetSignInChoicesCallback(int (*)(int)) override;
    void GetSignInEntries() override;
    void LoadAllMiiData() override;
    void FreeAllMiiData() override;
    void GetNumSysUserMiis() override;
    void GetNumFavouriteMiis() override;
    void GetNumGuestMiis() override;
    void GetSysUserMiiData(int) override;
    void GetFavouriteMiiData(int) override;
    void GetGuestMiiData(int) override;
    void IsHasAchievementsFile(int) override;*/
    char gap8[40];
    void* qword30;
    char gap38[216];
    char char110;
    char gap111[1583];
    int dword740;
    int dword744;
    int dword748;
    int dword74C;
    void* qword750;
    void* qword758;
    void* qword760;
    void* qword768;
    char gap770[16];
    char byte780;
    __attribute__((aligned(2))) char byte782;
    int dword784;
    int dword788;
    int dword78C;
    int dword790;
    uint16_t word794;
    uint16_t word796;
    char byte798;
    char gap799[2];
    char byte79B;
    void* qword7A0;
    void* qword7A8;
    void* qword7B0;
    int dword7B8;
    char gap7BC[12];
    int (*mSignInChoicesCallback)(int);
    int gap7D0[3];
    char byte7DC;
    void* qword7E0;
    char gap7E8[20];
    int dword7FC;
    int dword800;
    void* qword808;
    int dword810;
    void* qword818;
    char gap820[20];
    uint16_t word834;
    uint16_t word836;
    uint16_t word838;
    uint16_t word83A;
    int dword83C;
    void* qword840;
    int dword848;
    void* qword850;
    int dword858;
    char byte85C;
    bool mIsInitalised;
    char gap85E;
    char byte85F;
    char byte860;
    char gap861[39];
    char byte888;
    char gap889[39];
    void* qword8B0;
    void* qword8B8;
    void* qword8C0;
    void* qword8C8;
    void* qword8D0;
    void* qword8D8;
    void* qword8E0;
    void* qword8E8;
    void* qword8F0;
    char gap8F8[152];
    std::unordered_map<int, int> map990;
    std::unordered_map<int, int> map9B8;
    std::unordered_map<int, std::unordered_map<int, int>> map9E0;
    char gapA04[76];
    void* qwordA50;
    void* qwordA58;
    void* qwordA60;
    void* qwordA68;
    void* qwordA70;
    void* qwordA78;
    void* qwordA80;
    void* qwordA88;
    void* qwordA90;
    void* qwordA98;
    void* qwordAA0;
    void* qwordAA8;
    char gapAB0[70];
    std::unordered_map<int, int> mapAF8;
    std::unordered_map<int, int> mapB20;
    std::unordered_map<int, int> mapB48;
    std::unordered_map<int, int> mapB70;
    char gapB98[32];  // another map?
    void (*mOnAwardHandler)();
    void* mAwardHandlerVar;
    void* qwordBD0;
    void* qwordBD8;
    void* qwordBE0;
    void* qwordBE8;
    int dwordBF0;
    char gapBF4[1580];
    void* qword1220;
    void* qword1228;
    void* qword1230;
    void* qword1238;
    void* qword1240;
    void* qword1248;
    char gap1250[30];
};
