#pragma once

#include "Minecraft.World/ArrayWithLength.h"
#include "Minecraft.World/InteractionHand.h"
#include "Minecraft.World/eINSTANCEOF.h"
#include "Minecraft.World/entity/CommandSender.h"
#include "Minecraft.World/sounds/SoundSource.h"
#include <cstdint>
#include <memory>
#include <set>

#include "types.h"

enum MoverType { SELF, PLAYER, PISTON, SHULKER_BOX, SHULKER };
class Block;
class BlockPos;
class BlockState;
class SoundEvent;
class Material;
class Level;
class DamageSource;
class Player;
class Item;
class CompoundTag;
class ItemInstance;
class Direction;
class LightningBolt;
class Team;
class EntityTooltipDataHolder;
class EquipmentSlot;
class AABB;
class Rotation;
class LivingEntity;
class Explosion;
class ServerPlayer;
class Mirror;
class EntityDataAccessor_Base;
class Vec3;
class Random;
class SynchedEntityData;

class Entity : public std::enable_shared_from_this<Entity>, public CommandSender {
public:
    Entity(Level*, bool);

    void sendMessage(ClientboundChatPacket::EChatPacketMessage, int*, uint, std::wstring*, uint) override;
    bool hasPermission(EGameCommand) override;
    std::wstring getNetworkName() override;
    BlockPos getCommandSenderBlockPosition() override;
    Vec3 getCommandSenderWorldPosition() override;
    Level* getCommandSenderWorld() override;
    void getCommandSenderEntity() override;
    bool isSendMessageEnabled() override;
    void setCommandStats(CommandStats::CommandStatType, int) override;
    void getServer() override;
    virtual ~Entity();
    virtual eINSTANCEOF GetType() = 0;
    virtual void fjDerivedCtorCalls();
    virtual void kill();
    virtual void defineSynchedData() = 0;
    virtual void resetPos();
    virtual void remove();
    virtual void setDropContainerContent(bool);
    virtual void setSize(float, float);
    virtual void setPos(double, double, double);
    virtual void tick();
    virtual void baseTick();
    virtual void processDimensionDelay();
    virtual int getPortalWaitTime();
    virtual void setSecondsOnFire(int);
    virtual void clearFire();
    virtual void outOfWorld();
    virtual void move(MoverType, double, double, double, bool);
    virtual void updateDeltaAfterMove(Block*, double, double, double, double&, double&, double&);
    virtual void setLocationFromBoundingbox();
    virtual void getSwimSound();
    virtual void getSwimSplashSound();
    virtual void checkInsideBlocks();
    virtual void onInsideBlock(const BlockState*);
    virtual void playStepSound(const BlockPos&, Block*);
    virtual float playFlySound(float);
    virtual bool makeFlySound();
    virtual void playSound(const SoundEvent*, float, float);
    virtual bool isSilent();
    virtual void setSilent(bool);
    virtual bool isNoGravity();
    virtual void setNoGravity(bool);
    // more understandable would be "canMakeStepSound" or "shouldMakeStepSound"
    virtual bool makeStepSound();
    virtual void checkFallDamage(double, bool, Block*, const BlockPos&);
    virtual AABB* getCollideBox();
    virtual void burn(int);
    virtual void causeFallDamage(float, float);
    virtual bool isInWater();
    virtual bool isOverWater();
    virtual void updateInWaterState();
    virtual void doWaterSplashEffect();
    virtual void updateSprintingState();
    virtual void doSprintParticleEffect();
    virtual bool isUnderLiquid(Material*);
    virtual void getLightColor();
    virtual void getBrightness();
    virtual void setLevel(Level*);
    virtual void moveTo(double, double, double, float, float);
    virtual void playerTouch(std::shared_ptr<Player>);
    virtual void push(std::shared_ptr<Entity>);
    virtual void push(double, double, double);
    virtual void markHurt();
    virtual void hurt(DamageSource*, float);
    virtual Vec3* getViewVector(float);
    virtual bool isPickable();
    virtual bool isPushable();
    virtual void awardKillScore(std::shared_ptr<Entity>, int, DamageSource*);
    virtual void shouldRender(double, double, double);
    virtual void shouldRender(double);
    virtual void shouldRenderAtSqrDistance(double);
    virtual void save(CompoundTag*);
    virtual void load(CompoundTag*);
    virtual void repositionEntityAfterLoad();
    virtual void readAdditionalSaveData(CompoundTag*) = 0;
    virtual void addAdditonalSaveData(CompoundTag*) = 0;
    virtual void readAdditionContructionTag_4(CompoundTag*);
    virtual void getAdditionContructionTag();
    virtual void spawnAtLocation(Item*, int);
    virtual void spawnAtLocation(Item*, int, float);
    virtual void spawnAtLocation(not_null_ptr<ItemInstance>, float);
    virtual bool isAlive();
    virtual bool isInWall();
    virtual void interact(const std::shared_ptr<Player>&, InteractionHand::EInteractionHand);
    virtual void getCollideAgainstBox(std::shared_ptr<Entity>);
    virtual void rideTick();
    virtual void positionRider(const std::shared_ptr<Entity>&);
    virtual void onPassengerTurned(std::shared_ptr<Entity>);
    virtual void getRidingHeight();
    virtual void getRideHeight();
    virtual void startRiding(std::shared_ptr<Entity>);
    virtual void startRiding(std::shared_ptr<Entity>, bool);
    virtual void GetInteractTooltip(const EntityTooltipDataHolder&);
    virtual void GetHitTooltip(const EntityTooltipDataHolder&);
    virtual void HideUseTooltips();
    virtual void canRide(std::shared_ptr<Entity>);
    virtual void ejectPassengers();
    virtual void stopRiding();
    virtual void stopRidingBeforeTeleport();
    virtual void addPassenger(std::shared_ptr<Entity>);
    virtual void removePassenger(std::shared_ptr<Entity>);
    virtual void canAddPassenger(std::shared_ptr<Entity>);
    virtual void lerpTo(double, double, double, float, float, int, bool);
    virtual void getPickRadius();
    virtual Vec3* getLookAngle();
    virtual void getRotationVector();
    virtual void getForward();
    virtual void handleInsidePortal(const BlockPos&);
    virtual void getDimensionChangingDelay();
    virtual void lerpMotion(double, double, double);
    virtual void handleEntityEvent(unsigned char, int);
    virtual void animateHurt();
    virtual void getHandSlots();
    virtual void getArmorSlots();
    virtual void getAllSlots();
    virtual void setItemSlot(const EquipmentSlot*, not_null_ptr<ItemInstance>);
    virtual bool isOnFire();
    virtual bool isPassenger();
    virtual bool isVehicle();
    virtual bool isSneaking();
    virtual void setSneaking(bool);
    virtual bool isIdle();
    virtual void setIsIdle(bool);
    virtual bool isSprinting();
    virtual void setSprinting(bool);
    virtual bool isGlowing();
    virtual void setGlowing(bool);
    virtual bool isInvisible();
    virtual bool isInvisibleTo(std::shared_ptr<Player>);
    virtual void getTeam();
    virtual bool isAlliedTo(std::shared_ptr<Entity>);
    virtual bool isAlliedTo(Team*);
    virtual void setInvisible(bool);
    virtual void ShouldRenderShadow();
    virtual void canFly();
    virtual void thunderHit(const LightningBolt*);
    virtual void killed(std::shared_ptr<LivingEntity>);
    virtual void checkInBlock(double, double, double);
    virtual void spawnEatParticles(const ItemInstance&, int);
    virtual void makeStuckInWeb();
    virtual void getName();
    virtual bool isInvulnerableTo(DamageSource*);
    virtual bool isInvulnerable();
    virtual void setInvulnerable(bool);
    virtual void getSubEntities();
    virtual bool is(std::shared_ptr<Entity>);
    virtual void getYHeadRot();
    virtual void setYHeadRot(float);
    virtual void setYBodyRot(float);
    virtual bool isAttackable();
    virtual void skipAttackInteraction(std::shared_ptr<Entity>);
    virtual void copyPosition(std::shared_ptr<Entity>);
    virtual void changeDimension(int);
    virtual void canChangeDimensions();
    virtual void getBlockExplosionResistance(Explosion*, Level*, const BlockPos&);
    virtual void shouldBlockExplode(Explosion*, Level*, const BlockPos&, float);
    virtual void getMaxFallDistance();
    virtual void getPortalEntranceBlock();
    virtual void getPortalEntranceOffset();
    virtual void getPortalEntranceForwards();
    virtual bool isIgnoringBlockTriggers();
    virtual void displayFireAnimation();
    virtual void setUUID(const std::wstring&);
    virtual void getUUID();
    virtual void getStringUUID();
    virtual bool isPushedByWater();
    virtual void getViewScale();
    virtual void setViewScale(double);
    virtual std::wstring getDisplayName();
    virtual void setCustomName(const std::wstring&, const std::wstring&, bool);
    virtual void getCustomName();
    virtual void hasCustomName();
    virtual void setCustomNameVisible(bool);
    virtual bool isCustomNameVisible();
    virtual void teleportTo(double, double, double);
    virtual void shouldShowName();
    virtual void onSyncedDataUpdated(const EntityDataAccessor_Base*);
    virtual Direction* getDirection();
    virtual void getMotionDirection();
    virtual void broadcastToPlayer(std::shared_ptr<ServerPlayer>);
    virtual const AABB* getBoundingBox();
    virtual void getBoundingBoxForCulling();
    virtual void setBoundingBox(AABB*);
    virtual void getEyeHeight();
    virtual void setSlot(int, const not_null_ptr<ItemInstance>&);
    virtual void interactAt(const std::shared_ptr<Player>&, Vec3*, InteractionHand::EInteractionHand);
    virtual void ignoreExplosion();
    virtual void startSeenByPlayer(std::shared_ptr<ServerPlayer>);
    virtual void stopSeenByPlayer(std::shared_ptr<ServerPlayer>);
    virtual void rotate(Rotation*);
    virtual void mirror(Mirror*);
    virtual void onlyOpCanSetNbt();
    virtual void checkAndResetTeleportedFlag();
    virtual void getControllingPassenger();
    virtual void getPassengers();
    virtual void hasPassenger(std::shared_ptr<Entity>);
    virtual void hasPassenger(eINSTANCEOF);
    virtual void fillIndirectPassengers(eINSTANCEOF, std::set<std::shared_ptr<Entity>>*);
    virtual void getIndirectPassengers(eINSTANCEOF);
    virtual void getIndirectPassengers();
    virtual void getRootVehicle();
    virtual bool isPassengerOfSameVehicle(std::shared_ptr<Entity>);
    virtual void hasIndirectPassenger(std::shared_ptr<Entity>);
    virtual void hasIndirectPassenger(eINSTANCEOF);
    virtual bool isControlledByLocalInstance();
    virtual void getVehicle();
    virtual void getPistonPushReaction();
    virtual SoundSource::ESoundSource getSoundSource();
    virtual bool isCreative();
    virtual bool isDespawnProtected();
    virtual void setDespawnProtected();
    virtual void couldWander();
    virtual void canCreateParticles();
    virtual void stopCurrentLerp();
    virtual bool PositionLocked_4();
    virtual void SetPositionLocked_4(bool);
    virtual void TakeGlideCollisionDamage_4();
    virtual void SetGlideCollisionDamage_4(bool);
    virtual double GetLiftForceModifier_4();
    virtual void SetLiftForceModifier_4(double);
    virtual void onLoadedFromSave_4();
    virtual bool isUsingItemFlag_4();
    virtual void setUsingItemFlag_4(bool);
    virtual void getFireImmuneTicks();

    Vec3 getPos(float);
    bool isType(eINSTANCEOF);
    void setSharedFlag(int, bool);
    Vec3* calculateViewVector(float, float);
    int getId();
    bool isInLava();
    void moveRelative(float, float, float, float);
    bool isFree(double, double, double);
    void fjCheckDerivedConstruction();

    int mId;
    bool mBlocksBuilding;
    std::vector<Entity> mPassengers;
    int mBoardingCooldown;
    std::shared_ptr<Entity> mVehicle;
    bool mForcedLoading;
    Level* mLevel;
    double mXo;
    double mYo;
    double mZo;
    double mX;
    double mY;
    double mZ;
    Vec3 mDeltaMovement;
    float mYRot;
    float mXRot;
    float mYRotO;
    float mXRotO;
    AABB* mBoundingBox;
    bool mOnGround;
    bool mHorizontalCollision;
    bool mVerticalCollision;
    bool mCollision;
    bool mVelocityChanged;
    int mFire;
    void* mFillererek[2];
    int dwordE0;
    int dwordE4;
    int dwordE8;
    bool mIsInWeb;
    bool mOutsideWorldBorder;
    bool mCipa;
    bool mRemoved;
    float mWidth;
    float mHeight;
    float mWalkDistO;
    float mWalkDist;
    float mMoveDist;
    float mFallDistance;
    uint16_t idk;
    uint16_t mFallTicks2;
    float mNextStep;
    float mNextFlap;
    double mXOld;
    double mYOld;
    double mZOld;
    float mMaxUpStep;
    bool mNoPhysics;
    void* mUnk138;
    Random* mRand;
    int mTickCount;
    bool mInWater;
    int mInvulnerableTime;
    bool mFirstTick;
    bool mIsImmuneToFire;
    SynchedEntityData* mEntityData;
    void* qword160;
    char gap168[52];
    int mChangingDimensionDelay;
    bool mIsInsidePortal;
    int mPortalTime;
    int mDimension;
    BlockPos mPortalEntranceBlock;
    Vec3* mPortalEntranceOffset;
    Direction* mPortalEntranceForwards;
    void* qword1C8;
    char gap1D0[8];
    void* qword1D8;
    void* qword1E0;
    void* qword1E8;
    char gap1F0[8];
    void* qword1F8;
    void* qword200;
    char gap208[8];
    void* qword210;
    int dword218;
    char gap21C[4];
    bool mGlowing;
    void* qword228;
    char gap230[8];
    void* qword238;
    void* qword240;
    arrayWithLength<double> mPistonDeltas;
    long mPistonDeltasGameTime;
    int mType;
    void* qword268;
    void* qword270;
    void* qword278;
    void* qword280;
    void* qword288;
    int dword290;
    void* qword298;
    void* qword2A0;
    void* fillToSize0x2B8[2];  // I assume that Entity is 0x2B8 in size because if you look at typeinfo it
                               // seems that second type is placed on 0x2B8 (idk how to put this in words)
};

ASSERT_SIZEOF(Entity, 0x2B8)
