#pragma once
#include "C_4JProfile.h"

enum eUpsellType {};
enum eUpsellResponse {};

#include <cstdint>
class CProfile : public C_4JProfile {
public:
    static CProfile* sInstance;

    CProfile();

    void Initialise(const void*, const void*, unsigned short, unsigned int, unsigned int, unsigned int*, int,
                    unsigned int*) override;
    int GetLockedProfile() override;
    void
    SetLockedProfile(int) override;  // guessing int here is flags provided by the OS when getting the user
    bool IsSignedInt(int) override;
    bool IsSignedInLive(int) override;
    bool IsSigningIn(int) override;
    bool IsGuest(int) override;
    virtual void sub_710079238C();  // Wii U says CProfile::RequestSignInUI
    void SignInUser(void*, int);    // void * used to be MiiDataEntry
    virtual void sub_710079239C();
    virtual void sub_71007923AC();
    virtual void sub_71007923C0();
    virtual void sub_71007923F0();
    virtual void sub_7100792640();
    virtual void sub_710079188C();
    virtual void sub_7100791B48();
    virtual void sub_7100791B78();
    virtual void sub_7100792734();
    virtual void sub_71007926EC();
    virtual void sub_7100792BE8();
    virtual void sub_7100791DB0();
    virtual void sub_7100791F5C();
    virtual void sub_7100791FFC();
    virtual void sub_710079201C();
    virtual void sub_7100792750();
    virtual void sub_7100792028();
    virtual void sub_7100792184();
    virtual void sub_7100792754();
    virtual void sub_71007927BC();
    virtual void sub_7100791ECC();
    virtual void sub_7100791ED4();
    virtual void sub_7100791EDC();
    virtual void sub_7100794B3C();
    virtual void sub_7100794A3C();
    virtual void sub_7100794A78();
    virtual void sub_7100792A30();
    virtual void sub_7100792A54();
    virtual void sub_7100792AAC();
    virtual void sub_7100792BFC();
    virtual void sub_7100792C04();
    virtual void sub_7100792C0C();
    bool IsFullVersion() override;
    void SetFullVersion(bool v) override;
    void SetSignInChangeCallback(void (*)(void*, bool, unsigned int), void*) override;
    virtual void sub_7100792C1C();
    virtual void sub_7100794A20();
    virtual void sub_7100794A2C();
    virtual void sub_7100794A34();
    virtual void sub_7100794B58();
    virtual void sub_7100794B50();
    void SetProfileReadErrorCallback(void (*)(void*), void*) override;
    virtual void sub_710079235C();
    virtual void sub_71007927C0();
    virtual void AwardManagerOnCreate();
    virtual void sub_71007A2B24();
    virtual void sub_71007A2DE4();
    virtual void sub_71007A2DEC();
    virtual void sub_71007A2DF4();
    virtual void sub_71007A2894();
    virtual void sub_71007A2994();
    virtual void SetOnAwardHandler(void (*)(), void*);
    virtual void sub_7100792C4C();
    virtual void sub_7100794818();
    virtual void sub_7100793C60();
    virtual void sub_7100794848();
    virtual void sub_7100793B3C();
    virtual void sub_7100793CE0();
    virtual void sub_7100794404();
    virtual void sub_71007946A8();
    virtual void sub_71007946B0();
    virtual void sub_7100794804();
    virtual void sub_7100794810();
    virtual void sub_7100792C38();
    virtual void sub_710079457C();
    virtual void sub_710079493C();
    virtual void SetUpsellCallback(void (*)(void*, eUpsellType, eUpsellResponse, int), void*);
    virtual void sub_7100794B6C();
    virtual void sub_71007929E4();
    virtual void sub_7100792A08();
    virtual void sub_7100792A24();
    virtual void sub_7100792BF4();
    virtual void sub_7100792AF0();
    virtual void sub_7100792AF4();
    virtual void sub_7100792BE0();
    virtual void sub_7100792B80();
    virtual void sub_7100792B7C();
    virtual void sub_7100792B74();
    virtual void sub_7100792B88();
    virtual void sub_7100792BC8();
    virtual void sub_7100792BD0();
    virtual void sub_7100792BD8();
    virtual void SetSignInChoicesCallback(int (*)(int));
    virtual void sub_7100792C44();
    virtual void sub_7100791DAC();
    virtual void sub_7100791D54();
    // virtuals are completly different than WiiU, this class is completly different

    /*virtual void GetLockedProfile();
    virtual void SetLockedProfile(int);
    virtual void IsSignedIn(int);
    virtual void IsSignedInLive(int);
    virtual void IsSigningIn(int);
    virtual void IsGuest(int);
    virtual void RequestSignInUI(bool,bool,bool,bool,bool,int (*)(void *,bool,int,bool),void *,int);
    virtual void SignInUser(MiiDataEntry *,int);
    virtual void SignOutUser(FFLCreateID &);
    virtual void SignOutUser(int);
    virtual void SetUserSigningIn(int,bool);
    virtual void DisplayOfflineProfile(int (*)(void *,bool,int),void *,int);
    virtual void sub_32F9A00();
    virtual void SetPrimaryPlayerChanged(bool);
    virtual void QuerySigninStatus();
    virtual void GetXUID(int,PlayerUID *,bool);
    virtual void sub_32F9D8C();
    virtual void AllowedToPlayMultiplayer(int);
    virtual void StartTrialGame();
    virtual void sub_32F9DB8();
    virtual void CanViewPlayerCreatedContent(int,bool,PlayerUID *,unsigned int);
    virtual void GetProfileAvatar(int,int (*)(void *,unsigned char *,unsigned int),void *);
    virtual void CancelProfileAvatarRequest();
    virtual void SetGetStringFunc(wchar_t const *(*)(int));
    virtual void SetPlayerListTitleID(int);
    virtual void SetFatalTrophyErrorID(int);
    virtual void GetPrimaryPad();
    virtual void SetPrimaryPad(int);
    virtual void ClearGameUsers();
    virtual void GetMiiName(int);
    virtual void GetGamertag(int);
    virtual void GetDisplayName(int);
    virtual void GetNetworkAccountID();
    virtual void IsFullVersion();
    virtual void SetFullVersion(bool);
    virtual void SetSignInChangeCallback(void (*)(void *,bool,unsigned int),void *);
    virtual void sub_32FB28C();
    virtual void sub_32FE5C8();
    virtual void RegionIsNorthAmerica();
    virtual void LocaleIsUSorCanada();
    virtual void GetLiveConnectionStatus();
    virtual void IsSystemUIDisplayed();
    virtual void SetProfileReadErrorCallback(void (*)(void *),void *);
    virtual void ResetProfileProcessState();
    virtual void Tick();
    virtual void sub_3313960();
    virtual void GetAwardId(int);
    virtual void GetAwardType(int);
    virtual void sub_3313988();
    virtual void sub_33143A8();
    virtual void sub_331455C();
    virtual void sub_3314610();
    virtual void Terminate();
    virtual void sub_32FC18C();
    virtual void sub_32FC1D4();
    virtual void RichPresenceRegisterContextString(int,int,int);
    virtual void RichPresenceInit(int,int);
    virtual void sub_32FE04C();
    virtual void sub_32FE0E4();
    virtual void SetRichPresenceSettingFn(int (*)(void const *));
    virtual void SetRichPresenceGameModeData(nn::fp::GameMode &);
    virtual void SetFriendPresenceChangeCallback(void (*)(unsigned int,void *),void *);
    virtual void SetRichPresenceGetStringCallback(wchar_t *(*)(int));
    virtual void SetFriendPresenceOnline(bool);
    virtual void sub_32FE60C();
    virtual void SetUpsellCallback(void (*)(void *,eUpsellType,eUpsellResponse,int),void *);
    virtual void SetDebugFullOverride(bool);
    virtual void SetNetworkStatus(bool);
    virtual void SetNetworkStatusWithoutSigninChange(bool);
    virtual void TryToConnectOnline();
    virtual void GetSignedInUsersMask();
    virtual void RefreshChatAndContentRestrictions(void (*)(void *),void *);
    virtual void sub_32FB908();
    virtual void SetServiceID(char *);
    virtual void HandleNetworkTicket(int,void *);
    virtual void SetMinimumAge(int);
    virtual void getUserID(int);
    virtual void getQuadrant(ACTUuid &);
    virtual void SetSignInChoicesCallback(int (*)(int));
    virtual void GetSignInEntries();
    virtual void LoadAllMiiData();
    virtual void FreeAllMiiData();
    virtual void GetNumSysUserMiis();
    virtual void GetNumFavouriteMiis();
    virtual void GetNumGuestMiis();
    virtual void GetSysUserMiiData(int);
    virtual void GetFavouriteMiiData(int);
    virtual void GetGuestMiiData(int);
    virtual void IsHasAchievementsFile(int);*/
    char gap8[40];
    void* qword30;
    char gap38[216];
    char char110;
    char gap111[1583];
    int dword740;
    int dword744;
    int dword748;
    int dword74C;
    void* qword750;
    void* qword758;
    void* qword760;
    void* qword768;
    char gap770[16];
    char byte780;
    __attribute__((aligned(2))) char byte782;
    int dword784;
    int dword788;
    int dword78C;
    int dword790;
    uint16_t word794;
    uint16_t word796;
    char byte798;
    char gap799[2];
    char byte79B;
    void* qword7A0;
    void* qword7A8;
    void* qword7B0;
    int dword7B8;
    char gap7BC[12];
    int (*mSignInChoicesCallback)(int);
    int gap7D0[3];
    char byte7DC;
    void* qword7E0;
    char gap7E8[20];
    int dword7FC;
    int dword800;
    void* qword808;
    int dword810;
    void* qword818;
    char gap820[20];
    uint16_t word834;
    uint16_t word836;
    uint16_t word838;
    uint16_t word83A;
    int dword83C;
    void* qword840;
    int dword848;
    void* qword850;
    int dword858;
    char byte85C;
    bool mIsInitalised;
    char gap85E;
    char byte85F;
    char byte860;
    char gap861[39];
    char byte888;
    char gap889[39];
    void* qword8B0;
    void* qword8B8;
    void* qword8C0;
    void* qword8C8;
    void* qword8D0;
    void* qword8D8;
    void* qword8E0;
    void* qword8E8;
    void* qword8F0;
    char gap8F8[152];
    void* qword990;
    void* qword998;
    void* qword9A0;
    void* qword9A8;
    int dword9B0;
    void* qword9B8;
    void* qword9C0;
    void* qword9C8;
    void* qword9D0;
    int dword9D8;
    void* qword9E0;
    void* qword9E8;
    void* qword9F0;
    void* qword9F8;
    int dwordA00;
    char gapA04[76];
    void* qwordA50;
    void* qwordA58;
    void* qwordA60;
    void* qwordA68;
    void* qwordA70;
    void* qwordA78;
    void* qwordA80;
    void* qwordA88;
    void* qwordA90;
    void* qwordA98;
    void* qwordAA0;
    void* qwordAA8;
    char gapAB0[272];
    void (*mOnAwardHandler)();
    void* mAwardHandlerVar;
    void* qwordBD0;
    void* qwordBD8;
    void* qwordBE0;
    void* qwordBE8;
    int dwordBF0;
    char gapBF4[1580];
    void* qword1220;
    void* qword1228;
    void* qword1230;
    void* qword1238;
    void* qword1240;
    void* qword1248;
    char gap1250[30];
};
