#include "net/minecraft/world/level/levelgen/CustomizableSourceSettings.h"

CustomizableSourceSettings::Builder::Builder() {
    setDefaults();
}

// NON_MATCHING: this is needed to be moved into header rather than here, then it will match
void CustomizableSourceSettings::Builder::setDefaults() {
    m_waterLakeChance = 4;
    m_lavaLakeChance = 80;
    m_fixedBiome = -1;
    m_biomeSize = 4;
    m_coordinateScale = 684.41;
    m_heightScale = 684.41;
    m_lowerLimitScale = 512.0;
    m_upperLimitScale = 512.0;
    m_depthNoiseScaleX = 200.0;
    m_depthNoiseScaleZ = 200.0;
    m_riverSize = 4;
    m_dirtSize = 33;
    m_dirtCount = 10;
    m_dirtMinHeight = 0;
    m_graniteCount = 10;
    m_graniteMinHeight = 0;
    m_dioriteCount = 10;
    m_dioriteMinHeight = 0;
    m_andesiteCount = 10;
    m_andesiteMinHeight = 0;
    m_depthNoiseScaleExponent = 0.5;
    m_ainNoiseScaleX = 80.0;
    m_andesiteMaxHeight = 80;
    m_coalSize = 17;
    m_ainNoiseScaleY = 160.0;
    m_ainNoiseScaleZ = 80.0;
    m_coalCount = 20;
    m_coalMinHeight = 0;
    m_ironCount = 20;
    m_ironMinHeight = 0;
    m_baseSize = 8.5;
    m_stretchY = 12.0;
    m_dirtMaxHeight = 128;
    m_gravelSize = 33;
    m_gravelMaxHeight = 128;
    m_graniteSize = 33;
    m_dungeonChance = 8;
    m_gravelCount = 8;
    m_gravelMinHeight = 0;
    m_ironMaxHeight = 64;
    m_goldSize = 9;
    m_redstoneCount = 8;
    m_redstoneMinHeight = 0;
    m_biomeDepthWeight = 1.0;
    m_biomeDepthOffset = 0.0;
    m_biomeScaleWeight = 1.0;
    m_biomeScaleOffset = 0.0;
    m_graniteMaxHeight = 80;
    m_dioriteSize = 33;
    m_dioriteMaxHeight = 80;
    m_andesiteSize = 33;
    m_goldCount = 2;
    m_goldMinHeight = 0;
    m_seaLevel = 63;
    m_redstoneMaxHeight = 16;
    m_diamondSize = 8;
    m_useCaves = 1;
    m_useDungeons = 1;
    m_useStrongholds = 1;
    m_useVillages = 1;
    m_useMineshafts = 1;
    m_useScatteredFeatures = 1;
    m_useOceanMonuments = 1;
    m_useWoodlandMansions = 1;
    m_byte52 = 1;
    m_useWaterLakes = 1;
    m_useLavaLakes = 1;
    m_useLavaOceans = 0;
    m_coalMaxHeight = 128;
    m_ironSize = 9;
    m_goldMaxHeight = 32;
    m_redstoneSize = 8;
    m_diamondCount = 1;
    m_diamondMinHeight = 0;
    m_diamondMaxHeight = 16;
    m_lapisSize = 7;
    m_lapisCount = 1;
    m_lapisCenterHeight = 16;
    m_lapisSpread = 16;
}

CustomizableSourceSettings::Builder*
CustomizableSourceSettings::Builder::fromString(SuperflatConfig* config) {
    return new Builder();
}

CustomizableSourceSettings* CustomizableSourceSettings::Builder::build() {
    return new CustomizableSourceSettings(this);
}

CustomizableSourceSettings::CustomizableSourceSettings(CustomizableSourceSettings::Builder* builder) {
    this->m_coordinateScale = builder->m_coordinateScale;
    this->m_heightScale = builder->m_heightScale;
    this->m_lowerLimitScale = builder->m_lowerLimitScale;
    this->m_upperLimitScale = builder->m_upperLimitScale;
    this->m_depthNoiseScaleX = builder->m_depthNoiseScaleX;
    this->m_depthNoiseScaleZ = builder->m_depthNoiseScaleZ;
    this->m_depthNoiseScaleExponent = builder->m_depthNoiseScaleExponent;
    this->m_ainNoiseScaleX = builder->m_ainNoiseScaleX;
    this->m_ainNoiseScaleY = builder->m_ainNoiseScaleY;
    this->m_ainNoiseScaleZ = builder->m_ainNoiseScaleZ;
    this->m_baseSize = builder->m_baseSize;
    this->m_stretchY = builder->m_stretchY;
    this->m_biomeDepthWeight = builder->m_biomeDepthWeight;
    this->m_biomeDepthOffset = builder->m_biomeDepthOffset;
    this->m_biomeScaleWeight = builder->m_biomeScaleWeight;
    this->m_biomeScaleOffset = builder->m_biomeScaleOffset;
    this->m_seaLevel = builder->m_seaLevel;
    this->m_useCaves = builder->m_useCaves;
    this->m_useDungeons = builder->m_useDungeons;
    this->m_dungeonChance = builder->m_dungeonChance;
    this->m_useStrongholds = builder->m_useStrongholds;
    this->m_useVillages = builder->m_useVillages;
    this->m_useMineshafts = builder->m_useMineshafts;
    this->m_useScatteredFeatures = builder->m_useScatteredFeatures;
    this->m_useOceanMonuments = builder->m_useOceanMonuments;
    this->m_useWoodlandMansions = builder->m_useWoodlandMansions;
    this->m_byte52 = builder->m_byte52;
    this->m_useWaterLakes = builder->m_useWaterLakes;
    this->m_waterLakeChance = builder->m_waterLakeChance;
    this->m_useLavaLakes = builder->m_useLavaLakes;
    this->m_lavaLakeChance = builder->m_lavaLakeChance;
    this->m_useLavaOceans = builder->m_useLavaOceans;
    this->m_fixedBiome = builder->m_fixedBiome;
    this->m_biomeSize = builder->m_biomeSize;
    this->m_riverSize = builder->m_riverSize;
    this->m_dirtSize = builder->m_dirtSize;
    this->m_dirtCount = builder->m_dirtCount;
    this->m_dirtMinHeight = builder->m_dirtMinHeight;
    this->m_dirtMaxHeight = builder->m_dirtMaxHeight;
    this->m_gravelSize = builder->m_gravelSize;
    this->m_gravelCount = builder->m_gravelCount;
    this->m_gravelMinHeight = builder->m_gravelMinHeight;
    this->m_gravelMaxHeight = builder->m_gravelMaxHeight;
    this->m_graniteSize = builder->m_graniteSize;
    this->m_graniteCount = builder->m_graniteCount;
    this->m_graniteMinHeight = builder->m_graniteMinHeight;
    this->m_graniteMaxHeight = builder->m_graniteMaxHeight;
    this->m_dioriteSize = builder->m_dioriteSize;
    this->m_dioriteCount = builder->m_dioriteCount;
    this->m_dioriteMinHeight = builder->m_dioriteMinHeight;
    this->m_dioriteMaxHeight = builder->m_dioriteMaxHeight;
    this->m_andesiteSize = builder->m_andesiteSize;
    this->m_andesiteCount = builder->m_andesiteCount;
    this->m_andesiteMinHeight = builder->m_andesiteMinHeight;
    this->m_andesiteMaxHeight = builder->m_andesiteMaxHeight;
    this->m_coalSize = builder->m_coalSize;
    this->m_coalCount = builder->m_coalCount;
    this->m_coalMinHeight = builder->m_coalMinHeight;
    this->m_coalMaxHeight = builder->m_coalMaxHeight;
    this->m_ironSize = builder->m_ironSize;
    this->m_ironCount = builder->m_ironCount;
    this->m_ironMinHeight = builder->m_ironMinHeight;
    this->m_ironMaxHeight = builder->m_ironMaxHeight;
    this->m_goldSize = builder->m_goldSize;
    this->m_goldCount = builder->m_goldCount;
    this->m_goldMinHeight = builder->m_goldMinHeight;
    this->m_goldMaxHeight = builder->m_goldMaxHeight;
    this->m_redstoneSize = builder->m_redstoneSize;
    this->m_redstoneCount = builder->m_redstoneCount;
    this->m_redstoneMinHeight = builder->m_redstoneMinHeight;
    this->m_redstoneMaxHeight = builder->m_redstoneMaxHeight;
    this->m_diamondSize = builder->m_diamondSize;
    this->m_diamondCount = builder->m_diamondCount;
    this->m_diamondMinHeight = builder->m_diamondMinHeight;
    this->m_diamondMaxHeight = builder->m_diamondMaxHeight;
    this->m_lapisSize = builder->m_lapisSize;
    this->m_lapisCount = builder->m_lapisCount;
    this->m_lapisCenterHeight = builder->m_lapisCenterHeight;
    this->m_lapisSpread = builder->m_lapisSpread;
}
