#include "Minecraft.Client/renderer/texture/TextureAtlas.h"
#include "Minecraft.Client/renderer/texture/TextureAtlasSprite.h"

#include "Minecraft.Client/renderer/texture/atlases/ClockAtlasSprite.h"
#include "Minecraft.Client/renderer/texture/atlases/CompassAtlasSprite.h"

#define TERRAIN_RATIO (16.f / 512.f)  // 16 is one icon size, 512 terrain image height
#define ITEM_RATIO (16.f / 272.f)     // 16 is one icon size, 272 item image height

#define RATIO (16.f / 256.f)

TextureAtlas::~TextureAtlas() {}

// NON_MATCHING: I don't have a damn clue
TextureAtlasSprite* TextureAtlas::registerIcon(const std::wstring& name) {
    if (!name.empty()) {
        if (auto sprite = this->mTextureAtlasSprites.find(name); sprite != this->mTextureAtlasSprites.end())
            return sprite->second;
    }

    return this->mMissingAtlasSprite;
}

int TextureAtlas::getIconType() {
    return this->mIconType;
}

void TextureAtlas::addIcon(bool terrain, int y, int x, const std::wstring& id) {
    float final_ratio = terrain ? TERRAIN_RATIO : ITEM_RATIO;
    this->mTextureAtlasSprites[id]
        = new TextureAtlasSprite(id, id, x * RATIO, final_ratio * y, (x + 1) * RATIO, final_ratio * (y + 1));
}

void TextureAtlas::addIconWithName(bool terrain, int y, int x, const std::wstring& id,
                                   const std::wstring& name) {
    float final_ratio = terrain ? TERRAIN_RATIO : ITEM_RATIO;
    this->mTextureAtlasSprites[id] = new TextureAtlasSprite(id, name, x * RATIO, final_ratio * y,
                                                            (x + 1) * RATIO, final_ratio * (y + 1));
}

void TextureAtlas::loadUVs() {
    if (this->mTextureAtlasSprites.empty()) {
        for (auto& pair : this->mTextureAtlasSprites) {
            delete pair.second;
        }
        this->mTextureAtlasSprites.clear();
        if (this->mIconType) {
            this->addIcon(false, 0, 0, L"helmetCloth");
            this->addIcon(false, 0, 1, L"helmetChain");
            this->addIcon(false, 0, 2, L"helmetIron");
            this->addIcon(false, 0, 3, L"helmetDiamond");
            this->addIcon(false, 0, 4, L"helmetGold");
            this->addIcon(false, 0, 5, L"flintAndSteel");
            this->addIcon(false, 0, 6, L"flint");
            this->addIcon(false, 0, 7, L"coal");
            this->addIcon(false, 0, 8, L"string");
            this->addIcon(false, 0, 9, L"seeds");
            this->addIcon(false, 0, 10, L"apple");
            this->addIcon(false, 0, 11, L"appleGold");
            this->addIcon(false, 0, 12, L"egg");
            this->addIcon(false, 0, 13, L"sugar");
            this->addIcon(false, 0, 14, L"snowball");
            this->addIcon(false, 0, 15, L"elytra");
            this->addIcon(false, 1, 0, L"chestplateCloth");
            this->addIcon(false, 1, 1, L"chestplateChain");
            this->addIcon(false, 1, 2, L"chestplateIron");
            this->addIcon(false, 1, 3, L"chestplateDiamond");
            this->addIcon(false, 1, 4, L"chestplateGold");
            this->addIcon(false, 1, 5, L"bow");
            this->addIcon(false, 1, 6, L"brick");
            this->addIcon(false, 1, 7, L"ingotIron");
            this->addIcon(false, 1, 8, L"feather");
            this->addIcon(false, 1, 9, L"wheat");
            this->addIcon(false, 1, 10, L"painting");
            this->addIcon(false, 1, 11, L"reeds");
            this->addIcon(false, 1, 12, L"bone");
            this->addIcon(false, 1, 13, L"cake");
            this->addIcon(false, 1, 14, L"slimeball");
            this->addIcon(false, 1, 15, L"broken_elytra");
            this->addIcon(false, 2, 0, L"leggingsCloth");
            this->addIcon(false, 2, 1, L"leggingsChain");
            this->addIcon(false, 2, 2, L"leggingsIron");
            this->addIcon(false, 2, 3, L"leggingsDiamond");
            this->addIcon(false, 2, 4, L"leggingsGold");
            this->addIcon(false, 2, 5, L"arrow");
            this->addIcon(false, 2, 6, L"end_crystal");
            this->addIcon(false, 2, 7, L"ingotGold");
            this->addIcon(false, 2, 8, L"sulphur");
            this->addIcon(false, 2, 9, L"bread");
            this->addIcon(false, 2, 10, L"sign");
            this->addIcon(false, 2, 11, L"doorWood");
            this->addIcon(false, 2, 12, L"doorIron");
            this->addIcon(false, 2, 13, L"bed");
            this->addIcon(false, 2, 14, L"fireball");
            this->addIcon(false, 2, 15, L"chorus_fruit");
            this->addIcon(false, 3, 0, L"bootsCloth");
            this->addIcon(false, 3, 1, L"bootsChain");
            this->addIcon(false, 3, 2, L"bootsIron");
            this->addIcon(false, 3, 3, L"bootsDiamond");
            this->addIcon(false, 3, 4, L"bootsGold");
            this->addIcon(false, 3, 5, L"stick");
            this->addIcon(false, 3, 6, L"compass");
            this->addIcon(false, 3, 7, L"diamond");
            this->addIcon(false, 3, 8, L"redstone");
            this->addIcon(false, 3, 9, L"clay");
            this->addIcon(false, 3, 10, L"paper");
            this->addIcon(false, 3, 11, L"book");
            this->addIcon(false, 3, 12, L"map");
            this->addIcon(false, 3, 13, L"seeds_pumpkin");
            this->addIcon(false, 3, 14, L"seeds_melon");
            this->addIcon(false, 3, 15, L"chorus_fruit_popped");
            this->addIcon(false, 4, 0, L"swordWood");
            this->addIcon(false, 4, 1, L"swordStone");
            this->addIcon(false, 4, 2, L"swordIron");
            this->addIcon(false, 4, 3, L"swordDiamond");
            this->addIcon(false, 4, 4, L"swordGold");
            this->addIcon(false, 4, 5, L"fishingRod_uncast");
            this->addIcon(false, 4, 6, L"clock");
            this->addIcon(false, 4, 7, L"bowl");
            this->addIcon(false, 4, 8, L"mushroomStew");
            this->addIcon(false, 4, 9, L"yellowDust");
            this->addIcon(false, 4, 10, L"bucket");
            this->addIcon(false, 4, 11, L"bucketWater");
            this->addIcon(false, 4, 12, L"bucketLava");
            this->addIcon(false, 4, 13, L"milk");
            this->addIcon(false, 4, 14, L"dyePowder_black");
            this->addIcon(false, 4, 15, L"dyePowder_gray");
            this->addIcon(false, 5, 0, L"shovelWood");
            this->addIcon(false, 5, 1, L"shovelStone");
            this->addIcon(false, 5, 2, L"shovelIron");
            this->addIcon(false, 5, 3, L"shovelDiamond");
            this->addIcon(false, 5, 4, L"shovelGold");
            this->addIcon(false, 5, 5, L"fishingRod_cast");
            this->addIcon(false, 5, 6, L"diode");
            this->addIcon(false, 5, 7, L"porkchopRaw");
            this->addIcon(false, 5, 8, L"porkchopCooked");
            this->addIcon(false, 5, 9, L"fishRaw");
            this->addIcon(false, 5, 10, L"fishCooked");
            this->addIcon(false, 5, 11, L"rottenFlesh");
            this->addIcon(false, 5, 12, L"cookie");
            this->addIcon(false, 5, 13, L"shears");
            this->addIcon(false, 5, 14, L"dyePowder_red");
            this->addIcon(false, 5, 15, L"dyePowder_pink");
            this->addIcon(false, 6, 0, L"pickaxeWood");
            this->addIcon(false, 6, 1, L"pickaxeStone");
            this->addIcon(false, 6, 2, L"pickaxeIron");
            this->addIcon(false, 6, 3, L"pickaxeDiamond");
            this->addIcon(false, 6, 4, L"pickaxeGold");
            this->addIcon(false, 6, 5, L"bow_pull_0");
            this->addIcon(false, 6, 6, L"carrotOnAStick");
            this->addIcon(false, 6, 7, L"leather");
            this->addIcon(false, 6, 8, L"saddle");
            this->addIcon(false, 6, 9, L"beefRaw");
            this->addIcon(false, 6, 10, L"beefCooked");
            this->addIcon(false, 6, 11, L"enderPearl");
            this->addIcon(false, 6, 12, L"blazeRod");
            this->addIcon(false, 6, 13, L"melon");
            this->addIcon(false, 6, 14, L"dyePowder_green");
            this->addIcon(false, 6, 15, L"dyePowder_lime");
            this->addIcon(false, 7, 0, L"hatchetWood");
            this->addIcon(false, 7, 1, L"hatchetStone");
            this->addIcon(false, 7, 2, L"hatchetIron");
            this->addIcon(false, 7, 3, L"hatchetDiamond");
            this->addIcon(false, 7, 4, L"hatchetGold");
            this->addIcon(false, 7, 5, L"bow_pull_1");
            this->addIcon(false, 7, 6, L"potatoBaked");
            this->addIcon(false, 7, 7, L"potato");
            this->addIcon(false, 7, 8, L"carrots");
            this->addIcon(false, 7, 9, L"chickenRaw");
            this->addIcon(false, 7, 10, L"chickenCooked");
            this->addIcon(false, 7, 11, L"ghastTear");
            this->addIcon(false, 7, 12, L"goldNugget");
            this->addIcon(false, 7, 13, L"netherStalkSeeds");
            this->addIcon(false, 7, 14, L"dyePowder_brown");
            this->addIcon(false, 7, 15, L"dyePowder_yellow");
            this->addIcon(false, 8, 0, L"hoeWood");
            this->addIcon(false, 8, 1, L"hoeStone");
            this->addIcon(false, 8, 2, L"hoeIron");
            this->addIcon(false, 8, 3, L"hoeDiamond");
            this->addIcon(false, 8, 4, L"hoeGold");
            this->addIcon(false, 8, 5, L"bow_pull_2");
            this->addIcon(false, 8, 6, L"potatoPoisonous");
            this->addIcon(false, 8, 7, L"minecart");
            this->addIcon(false, 8, 8, L"boat");
            this->addIcon(false, 8, 9, L"speckledMelon");
            this->addIcon(false, 8, 10, L"fermentedSpiderEye");
            this->addIcon(false, 8, 11, L"spiderEye");
            this->addIcon(false, 8, 12, L"potion");
            this->addIcon(false, 8, 12, L"glassBottle");
            this->addIcon(false, 8, 13, L"potion_contents");
            this->addIcon(false, 8, 14, L"dyePowder_blue");
            this->addIcon(false, 8, 15, L"dyePowder_light_blue");
            this->addIcon(false, 9, 0, L"helmetCloth_overlay");
            this->addIcon(false, 9, 1, L"spectral_arrow");
            this->addIcon(false, 9, 2, L"iron_horse_armor");
            this->addIcon(false, 9, 3, L"diamond_horse_armor");
            this->addIcon(false, 9, 4, L"gold_horse_armor");
            this->addIcon(false, 9, 5, L"comparator");
            this->addIcon(false, 9, 6, L"carrotGolden");
            this->addIcon(false, 9, 7, L"minecart_chest");
            this->addIcon(false, 9, 8, L"pumpkinPie");
            this->addIcon(false, 9, 9, L"monsterPlacer");
            this->addIcon(false, 9, 10, L"potion_splash");
            this->addIcon(false, 9, 11, L"eyeOfEnder");
            this->addIcon(false, 9, 12, L"cauldron");
            this->addIcon(false, 9, 13, L"blazePowder");
            this->addIcon(false, 9, 14, L"dyePowder_purple");
            this->addIcon(false, 9, 15, L"dyePowder_magenta");
            this->addIcon(false, 10, 0, L"chestplateCloth_overlay");
            this->addIcon(false, 10, 1, L"tipped_arrow_base");
            this->addIcon(false, 10, 2, L"dragon_breath");
            this->addIcon(false, 10, 3, L"name_tag");
            this->addIcon(false, 10, 4, L"lead");
            this->addIcon(false, 10, 5, L"netherbrick");
            this->addIcon(false, 10, 6, L"fish_clownfish_raw");
            this->addIcon(false, 10, 7, L"minecart_furnace");
            this->addIcon(false, 10, 8, L"charcoal");
            this->addIcon(false, 10, 9, L"monsterPlacer_overlay");
            this->addIcon(false, 10, 10, L"bed_overlay");
            this->addIcon(false, 10, 11, L"expBottle");
            this->addIcon(false, 10, 12, L"brewingStand");
            this->addIcon(false, 10, 13, L"magmaCream");
            this->addIcon(false, 10, 14, L"dyePowder_cyan");
            this->addIcon(false, 10, 15, L"dyePowder_orange");
            this->addIcon(false, 11, 0, L"leggingsCloth_overlay");
            this->addIcon(false, 11, 1, L"tipped_arrow_head");
            this->addIcon(false, 11, 2, L"potion_bottle_lingering");
            this->addIcon(false, 11, 3, L"barrier");
            this->addIcon(false, 11, 4, L"mutton_raw");
            this->addIcon(false, 11, 5, L"rabbit_raw");
            this->addIcon(false, 11, 6, L"fish_pufferfish_raw");
            this->addIcon(false, 11, 7, L"minecart_hopper");
            this->addIcon(false, 11, 8, L"hopper");
            this->addIcon(false, 11, 9, L"nether_star");
            this->addIcon(false, 11, 10, L"emerald");
            this->addIcon(false, 11, 11, L"writingBook");
            this->addIcon(false, 11, 12, L"writtenBook");
            this->addIcon(false, 11, 13, L"flowerPot");
            this->addIcon(false, 11, 14, L"dyePowder_silver");
            this->addIcon(false, 11, 15, L"dyePowder_white");
            this->addIcon(false, 12, 0, L"bootsCloth_overlay");
            this->addIcon(false, 12, 1, L"beetroot");
            this->addIcon(false, 12, 2, L"beetroot_seeds");
            this->addIcon(false, 12, 3, L"beetroot_soup");
            this->addIcon(false, 12, 4, L"mutton_cooked");
            this->addIcon(false, 12, 5, L"rabbit_cooked");
            this->addIcon(false, 12, 6, L"fish_salmon_raw");
            this->addIcon(false, 12, 7, L"minecart_tnt");
            this->addIcon(false, 12, 8, L"wooden_armorstand");
            this->addIcon(false, 12, 9, L"fireworks");
            this->addIcon(false, 12, 10, L"fireworks_charge");
            this->addIcon(false, 12, 11, L"fireworks_charge_overlay");
            this->addIcon(false, 12, 12, L"netherquartz");
            this->addIcon(false, 12, 13, L"map_empty");
            this->addIcon(false, 12, 14, L"frame");
            this->addIcon(false, 12, 15, L"enchantedBook");
            this->addIcon(false, 13, 0, L"door_acacia");
            this->addIcon(false, 13, 1, L"door_birch");
            this->addIcon(false, 13, 2, L"door_dark_oak");
            this->addIcon(false, 13, 3, L"door_jungle");
            this->addIcon(false, 13, 4, L"door_spruce");
            this->addIcon(false, 13, 5, L"rabbit_stew");
            this->addIcon(false, 13, 6, L"fish_salmon_cooked");
            this->addIcon(false, 13, 7, L"minecart_command_block");
            this->addIcon(false, 13, 8, L"acacia_boat");
            this->addIcon(false, 13, 9, L"birch_boat");
            this->addIcon(false, 13, 10, L"dark_oak_boat");
            this->addIcon(false, 13, 11, L"jungle_boat");
            this->addIcon(false, 13, 12, L"spruce_boat");
            this->addIcon(false, 13, 13, L"prismarine_shard");
            this->addIcon(false, 13, 14, L"prismarine_crystals");
            this->addIcon(false, 13, 15, L"leather_horse_armor_base");
            this->addIcon(false, 14, 0, L"structure_void");
            this->addIcon(false, 14, 1, L"map_filled_markings");
            this->addIcon(false, 14, 2, L"totem");
            this->addIcon(false, 14, 3, L"shulker_shell");
            this->addIcon(false, 14, 4, L"iron_nugget");
            this->addIcon(false, 14, 5, L"rabbit_foot");
            this->addIcon(false, 14, 6, L"rabbit_hide");
            this->addIconWithName(false, 14, 7, L"compassP0", L"compass");
            this->addIconWithName(false, 14, 8, L"compassP1", L"compass");
            this->addIconWithName(false, 14, 9, L"compassP2", L"compass");
            this->addIconWithName(false, 14, 10, L"compassP3", L"compass");
            this->addIconWithName(false, 14, 11, L"clockP0", L"clock");
            this->addIconWithName(false, 14, 12, L"clockP1", L"clock");
            this->addIconWithName(false, 14, 13, L"clockP2", L"clock");
            this->addIconWithName(false, 14, 14, L"clockP3", L"clock");
            this->addIcon(false, 14, 15, L"dragonFireball");
            this->addIcon(false, 15, 0, L"record_13");
            this->addIcon(false, 15, 1, L"record_cat");
            this->addIcon(false, 15, 2, L"record_blocks");
            this->addIcon(false, 15, 3, L"record_chirp");
            this->addIcon(false, 15, 4, L"record_far");
            this->addIcon(false, 15, 5, L"record_mall");
            this->addIcon(false, 15, 6, L"record_mellohi");
            this->addIcon(false, 15, 7, L"record_stal");
            this->addIcon(false, 15, 8, L"record_strad");
            this->addIcon(false, 15, 9, L"record_ward");
            this->addIcon(false, 15, 10, L"record_11");
            this->addIcon(false, 15, 11, L"record_where are we now");
            this->addIcon(false, 16, 0, L"leather_horse_armor_detail");

            TextureAtlasSprite* oldClockIcon;
            ClockAtlasSprite* newClockAtlasSprite;

            ClockAtlasSprite* baseClockAtlas = new ClockAtlasSprite();
            oldClockIcon = this->mTextureAtlasSprites[L"clock"];
            baseClockAtlas->initUVs(oldClockIcon->getU0(false), oldClockIcon->getV0(false),
                                    oldClockIcon->getU1(false), oldClockIcon->getV1(false));
            delete oldClockIcon;
            this->mTextureAtlasSprites[L"clock"] = baseClockAtlas;

            newClockAtlasSprite = new ClockAtlasSprite(0, baseClockAtlas);
            oldClockIcon = this->mTextureAtlasSprites[L"clockP0"];
            newClockAtlasSprite->initUVs(oldClockIcon->getU0(false), oldClockIcon->getV0(false),
                                         oldClockIcon->getU1(false), oldClockIcon->getV1(false));
            delete oldClockIcon;
            this->mTextureAtlasSprites[L"clockP0"] = newClockAtlasSprite;

            newClockAtlasSprite = new ClockAtlasSprite(1, baseClockAtlas);
            oldClockIcon = this->mTextureAtlasSprites[L"clockP1"];
            newClockAtlasSprite->initUVs(oldClockIcon->getU0(false), oldClockIcon->getV0(false),
                                         oldClockIcon->getU1(false), oldClockIcon->getV1(false));
            delete oldClockIcon;
            this->mTextureAtlasSprites[L"clockP1"] = newClockAtlasSprite;

            newClockAtlasSprite = new ClockAtlasSprite(2, baseClockAtlas);
            oldClockIcon = this->mTextureAtlasSprites[L"clockP2"];
            newClockAtlasSprite->initUVs(oldClockIcon->getU0(false), oldClockIcon->getV0(false),
                                         oldClockIcon->getU1(false), oldClockIcon->getV1(false));
            delete oldClockIcon;
            this->mTextureAtlasSprites[L"clockP2"] = newClockAtlasSprite;

            newClockAtlasSprite = new ClockAtlasSprite(3, baseClockAtlas);
            oldClockIcon = this->mTextureAtlasSprites[L"clockP3"];
            newClockAtlasSprite->initUVs(oldClockIcon->getU0(false), oldClockIcon->getV0(false),
                                         oldClockIcon->getU1(false), oldClockIcon->getV1(false));
            delete oldClockIcon;
            this->mTextureAtlasSprites[L"clockP3"] = newClockAtlasSprite;

            //

            TextureAtlasSprite* oldCompassIcon;
            CompassAtlasSprite* newCompassAtlasSprite;

            CompassAtlasSprite* baseCompassAtlas = new CompassAtlasSprite();
            oldCompassIcon = this->mTextureAtlasSprites[L"compass"];
            baseCompassAtlas->initUVs(oldCompassIcon->getU0(false), oldCompassIcon->getV0(false),
                                      oldCompassIcon->getU1(false), oldCompassIcon->getV1(false));
            delete oldCompassIcon;
            this->mTextureAtlasSprites[L"compass"] = baseCompassAtlas;

            newCompassAtlasSprite = new CompassAtlasSprite(0, baseCompassAtlas);
            oldCompassIcon = this->mTextureAtlasSprites[L"compassP0"];
            newCompassAtlasSprite->initUVs(oldCompassIcon->getU0(false), oldCompassIcon->getV0(false),
                                           oldCompassIcon->getU1(false), oldCompassIcon->getV1(false));
            delete oldCompassIcon;
            this->mTextureAtlasSprites[L"compassP0"] = newCompassAtlasSprite;

            newCompassAtlasSprite = new CompassAtlasSprite(1, baseCompassAtlas);
            oldCompassIcon = this->mTextureAtlasSprites[L"compassP1"];
            newCompassAtlasSprite->initUVs(oldCompassIcon->getU0(false), oldCompassIcon->getV0(false),
                                           oldCompassIcon->getU1(false), oldCompassIcon->getV1(false));
            delete oldCompassIcon;
            this->mTextureAtlasSprites[L"compassP1"] = newCompassAtlasSprite;

            newCompassAtlasSprite = new CompassAtlasSprite(2, baseCompassAtlas);
            oldCompassIcon = this->mTextureAtlasSprites[L"compassP2"];
            newCompassAtlasSprite->initUVs(oldCompassIcon->getU0(false), oldCompassIcon->getV0(false),
                                           oldCompassIcon->getU1(false), oldCompassIcon->getV1(false));
            delete oldCompassIcon;
            this->mTextureAtlasSprites[L"compassP2"] = newCompassAtlasSprite;

            newCompassAtlasSprite = new CompassAtlasSprite(3, baseCompassAtlas);
            oldCompassIcon = this->mTextureAtlasSprites[L"compassP3"];
            newCompassAtlasSprite->initUVs(oldCompassIcon->getU0(false), oldCompassIcon->getV0(false),
                                           oldCompassIcon->getU1(false), oldCompassIcon->getV1(false));
            delete oldCompassIcon;
            this->mTextureAtlasSprites[L"compassP3"] = newCompassAtlasSprite;
        } else {
            this->addIcon(true, 0, 0, L"grass_top");
            this->mTextureAtlasSprites[L"grass_top"]->setFlags(2);
            this->addIcon(true, 0, 1, L"stone");
            this->addIcon(true, 0, 2, L"dirt");
            this->addIcon(true, 0, 3, L"grass_side");
            this->mTextureAtlasSprites[L"grass_side"]->setFlags(1);
            this->addIcon(true, 0, 4, L"planks_oak");
            this->addIcon(true, 0, 5, L"stoneslab_side");
            this->addIcon(true, 0, 6, L"stoneslab_top");
            this->addIcon(true, 0, 7, L"brick");
            this->addIcon(true, 0, 8, L"tnt_side");
            this->addIcon(true, 0, 9, L"tnt_top");
            this->addIcon(true, 0, 10, L"tnt_bottom");
            this->addIcon(true, 0, 11, L"web");
            this->addIcon(true, 0, 12, L"flower_rose");
            this->addIcon(true, 0, 13, L"flower_dandelion");
            this->addIcon(true, 0, 14, L"portal");
            this->addIcon(true, 0, 15, L"sapling");
            this->addIcon(true, 1, 0, L"cobblestone");
            this->addIcon(true, 1, 1, L"bedrock");
            this->addIcon(true, 1, 2, L"sand");
            this->addIcon(true, 1, 3, L"gravel");
            this->addIcon(true, 1, 4, L"log_oak");
            this->addIcon(true, 1, 5, L"log_oak_top");
            this->addIcon(true, 1, 6, L"iron_block");
            this->addIcon(true, 1, 7, L"gold_block");
            this->addIcon(true, 1, 8, L"diamond_block");
            this->addIcon(true, 1, 9, L"emerald_block");
            this->addIcon(true, 1, 10, L"redstone_block");
            this->addIcon(true, 1, 11, L"dropper_front_horizontal");
            this->addIcon(true, 1, 12, L"mushroom_red");
            this->addIcon(true, 1, 13, L"mushroom_brown");
            this->addIcon(true, 1, 14, L"sapling_jungle");
            this->addIcon(true, 1, 15, L"fire_0");
            this->addIcon(true, 2, 0, L"gold_ore");
            this->addIcon(true, 2, 1, L"iron_ore");
            this->addIcon(true, 2, 2, L"coal_ore");
            this->addIcon(true, 2, 3, L"bookshelf");
            this->addIcon(true, 2, 4, L"cobblestone_mossy");
            this->addIcon(true, 2, 5, L"obsidian");
            this->addIcon(true, 2, 6, L"grass_side_overlay");
            this->addIcon(true, 2, 7, L"tallgrass");
            this->addIcon(true, 2, 8, L"dispenser_front_vertical");
            this->addIcon(true, 2, 9, L"beacon");
            this->addIcon(true, 2, 10, L"dropper_front_vertical");
            this->addIcon(true, 2, 11, L"workbench_top");
            this->addIcon(true, 2, 12, L"furnace_front");
            this->addIcon(true, 2, 13, L"furnace_side");
            this->addIcon(true, 2, 14, L"dispenser_front");
            this->addIcon(true, 2, 15, L"fire_1");
            this->addIcon(true, 3, 0, L"sponge");
            this->addIcon(true, 3, 1, L"glass");
            this->addIcon(true, 3, 2, L"diamond_ore");
            this->addIcon(true, 3, 3, L"redstone_ore");
            this->addIcon(true, 3, 4, L"leaves");
            this->addIcon(true, 3, 5, L"leaves_opaque");
            this->addIcon(true, 3, 6, L"stonebrick");
            this->addIcon(true, 3, 7, L"deadbush");
            this->addIcon(true, 3, 8, L"fern");
            this->addIcon(true, 3, 9, L"daylight_detector_top");
            this->addIcon(true, 3, 10, L"daylight_detector_side");
            this->addIcon(true, 3, 11, L"workbench_side");
            this->addIcon(true, 3, 12, L"workbench_front");
            this->addIcon(true, 3, 13, L"furnace_front_lit");
            this->addIcon(true, 3, 14, L"furnace_top");
            this->addIcon(true, 3, 15, L"sapling_spruce");
            this->addIcon(true, 4, 0, L"wool_colored_white");
            this->addIcon(true, 4, 1, L"mob_spawner");
            this->addIcon(true, 4, 2, L"snow");
            this->addIcon(true, 4, 3, L"ice");
            this->addIcon(true, 4, 4, L"snow_side");
            this->addIcon(true, 4, 5, L"cactus_top");
            this->addIcon(true, 4, 6, L"cactus_side");
            this->addIcon(true, 4, 7, L"cactus_bottom");
            this->addIcon(true, 4, 8, L"clay");
            this->addIcon(true, 4, 9, L"reeds");
            this->addIcon(true, 4, 10, L"jukebox_side");
            this->addIcon(true, 4, 11, L"jukebox_top");
            this->addIcon(true, 4, 12, L"waterlily");
            this->addIcon(true, 4, 13, L"mycel_side");
            this->addIcon(true, 4, 14, L"mycel_top");
            this->addIcon(true, 4, 15, L"sapling_birch");
            this->addIcon(true, 5, 0, L"torch_on");
            this->addIcon(true, 5, 1, L"door_wood_upper");
            this->addIcon(true, 5, 2, L"door_iron_upper");
            this->addIcon(true, 5, 3, L"ladder");
            this->addIcon(true, 5, 4, L"trapdoor");
            this->addIcon(true, 5, 5, L"iron_bars");
            this->addIcon(true, 5, 6, L"farmland_wet");
            this->addIcon(true, 5, 7, L"farmland_dry");
            this->addIcon(true, 5, 8, L"crops_0");
            this->addIcon(true, 5, 9, L"crops_1");
            this->addIcon(true, 5, 10, L"crops_2");
            this->addIcon(true, 5, 11, L"crops_3");
            this->addIcon(true, 5, 12, L"crops_4");
            this->addIcon(true, 5, 13, L"crops_5");
            this->addIcon(true, 5, 14, L"crops_6");
            this->addIcon(true, 5, 15, L"crops_7");
            this->addIcon(true, 6, 0, L"lever");
            this->addIcon(true, 6, 1, L"door_wood_lower");
            this->addIcon(true, 6, 2, L"door_iron_lower");
            this->addIcon(true, 6, 3, L"redstone_torch_on");
            this->addIcon(true, 6, 4, L"stonebrick_mossy");
            this->addIcon(true, 6, 5, L"stonebrick_cracked");
            this->addIcon(true, 6, 6, L"pumpkin_top");
            this->addIcon(true, 6, 7, L"netherrack");
            this->addIcon(true, 6, 8, L"soul_sand");
            this->addIcon(true, 6, 9, L"glowstone");
            this->addIcon(true, 6, 10, L"piston_top_sticky");
            this->addIcon(true, 6, 11, L"piston_top");
            this->addIcon(true, 6, 12, L"piston_side");
            this->addIcon(true, 6, 13, L"piston_bottom");
            this->addIcon(true, 6, 14, L"piston_inner_top");
            this->addIcon(true, 6, 15, L"stem_straight");
            this->addIcon(true, 7, 0, L"rail_normal_turned");
            this->addIcon(true, 7, 1, L"wool_colored_black");
            this->addIcon(true, 7, 2, L"wool_colored_gray");
            this->addIcon(true, 7, 3, L"redstone_torch_off");
            this->addIcon(true, 7, 4, L"log_spruce");
            this->addIcon(true, 7, 5, L"log_birch");
            this->addIcon(true, 7, 6, L"pumpkin_side");
            this->addIcon(true, 7, 7, L"pumpkin_face_off");
            this->addIcon(true, 7, 8, L"pumpkin_face_on");
            this->addIcon(true, 7, 9, L"cake_top");
            this->addIcon(true, 7, 10, L"cake_side");
            this->addIcon(true, 7, 11, L"cake_inner");
            this->addIcon(true, 7, 12, L"cake_bottom");
            this->addIcon(true, 7, 13, L"mushroom_block_skin_red");
            this->addIcon(true, 7, 14, L"mushroom_block_skin_brown");
            this->addIcon(true, 7, 15, L"stem_bent");
            this->addIcon(true, 8, 0, L"rail_normal");
            this->addIcon(true, 8, 1, L"wool_colored_red");
            this->addIcon(true, 8, 2, L"wool_colored_pink");
            this->addIcon(true, 8, 3, L"repeater_off");
            this->addIcon(true, 8, 4, L"leaves_spruce");
            this->addIcon(true, 8, 5, L"leaves_spruce_opaque");
            this->addIcon(true, 8, 6, L"bed_feet_top");
            this->addIcon(true, 8, 7, L"bed_head_top");
            this->addIcon(true, 8, 8, L"melon_side");
            this->addIcon(true, 8, 9, L"melon_top");
            this->addIcon(true, 8, 10, L"cauldron_top");
            this->addIcon(true, 8, 11, L"cauldron_inner");
            this->addIcon(true, 8, 12, L"sponge_wet");
            this->addIcon(true, 8, 13, L"mushroom_block_skin_stem");
            this->addIcon(true, 8, 14, L"mushroom_block_inside");
            this->addIcon(true, 8, 15, L"vine");
            this->addIcon(true, 9, 0, L"lapis_block");
            this->addIcon(true, 9, 1, L"wool_colored_green");
            this->addIcon(true, 9, 2, L"wool_colored_lime");
            this->addIcon(true, 9, 3, L"repeater_on");
            this->addIcon(true, 9, 4, L"glass_pane_top");
            this->addIcon(true, 9, 5, L"bed_feet_end");
            this->addIcon(true, 9, 6, L"bed_feet_side");
            this->addIcon(true, 9, 7, L"bed_head_side");
            this->addIcon(true, 9, 8, L"bed_head_end");
            this->addIcon(true, 9, 9, L"log_jungle");
            this->addIcon(true, 9, 10, L"cauldron_side");
            this->addIcon(true, 9, 11, L"cauldron_bottom");
            this->addIcon(true, 9, 12, L"brewing_stand_base");
            this->addIcon(true, 9, 13, L"brewing_stand");
            this->addIcon(true, 9, 14, L"endframe_top");
            this->addIcon(true, 9, 15, L"endframe_side");
            this->addIcon(true, 10, 0, L"lapis_ore");
            this->addIcon(true, 10, 1, L"wool_colored_brown");
            this->addIcon(true, 10, 2, L"wool_colored_yellow");
            this->addIcon(true, 10, 3, L"rail_golden");
            this->addIcon(true, 10, 4, L"redstone_dust_cross");
            this->addIcon(true, 10, 5, L"redstone_dust_line");
            this->addIcon(true, 10, 6, L"enchantment_top");
            this->addIcon(true, 10, 7, L"dragon_egg");
            this->addIcon(true, 10, 8, L"cocoa_2");
            this->addIcon(true, 10, 9, L"cocoa_1");
            this->addIcon(true, 10, 10, L"cocoa_0");
            this->addIcon(true, 10, 11, L"emerald_ore");
            this->addIcon(true, 10, 12, L"trip_wire_source");
            this->addIcon(true, 10, 13, L"trip_wire");
            this->addIcon(true, 10, 14, L"endframe_eye");
            this->addIcon(true, 10, 15, L"end_stone");
            this->addIcon(true, 11, 0, L"sandstone_top");
            this->addIcon(true, 11, 1, L"wool_colored_blue");
            this->addIcon(true, 11, 2, L"wool_colored_light_blue");
            this->addIcon(true, 11, 3, L"rail_golden_powered");
            this->addIcon(true, 11, 4, L"redstone_dust_cross_overlay");
            this->addIcon(true, 11, 5, L"redstone_dust_line_overlay");
            this->addIcon(true, 11, 6, L"enchantment_side");
            this->addIcon(true, 11, 7, L"enchantment_bottom");
            this->addIcon(true, 11, 8, L"diamondRing");
            this->addIcon(true, 11, 9, L"itemframe_back");
            this->addIcon(true, 11, 10, L"flower_pot");
            this->addIcon(true, 11, 11, L"comparator_off");
            this->addIcon(true, 11, 12, L"comparator_on");
            this->addIcon(true, 11, 13, L"rail_activator");
            this->addIcon(true, 11, 14, L"rail_activator_powered");
            this->addIcon(true, 11, 15, L"quartz_ore");
            this->addIcon(true, 12, 0, L"sandstone_side");
            this->addIcon(true, 12, 1, L"wool_colored_purple");
            this->addIcon(true, 12, 2, L"wool_colored_magenta");
            this->addIcon(true, 12, 3, L"detectorRail");
            this->addIcon(true, 12, 4, L"leaves_jungle");
            this->addIcon(true, 12, 5, L"leaves_jungle_opaque");
            this->addIcon(true, 12, 6, L"planks_spruce");
            this->addIcon(true, 12, 7, L"planks_jungle");
            this->addIcon(true, 12, 8, L"carrots_stage_0");
            this->addIcon(true, 12, 9, L"carrots_stage_1");
            this->addIcon(true, 12, 10, L"carrots_stage_2");
            this->addIcon(true, 12, 11, L"carrots_stage_3");
            this->addIcon(true, 12, 12, L"slime");
            this->addIcon(true, 12, 13, L"water");
            this->addIconSize(true, 12, 14, L"water_flow", 2, 2);
            this->addIcon(true, 13, 0, L"sandstone_bottom");
            this->addIcon(true, 13, 1, L"wool_colored_cyan");
            this->addIcon(true, 13, 2, L"wool_colored_orange");
            this->addIcon(true, 13, 3, L"redstoneLight");
            this->addIcon(true, 13, 4, L"redstoneLight_lit");
            this->addIcon(true, 13, 5, L"stonebrick_carved");
            this->addIcon(true, 13, 6, L"planks_birch");
            this->addIcon(true, 13, 7, L"anvil_base");
            this->addIcon(true, 13, 8, L"anvil_top_damaged_1");
            this->addIcon(true, 13, 9, L"quartz_block_chiseled_top");
            this->addIcon(true, 13, 10, L"quartz_block_lines_top");
            this->addIcon(true, 13, 11, L"quartz_block_top");
            this->addIcon(true, 13, 12, L"hopper_outside");
            this->addIcon(true, 13, 13, L"detectorRail_on");
            this->addIcon(true, 14, 0, L"nether_brick");
            this->addIcon(true, 14, 1, L"wool_colored_silver");
            this->addIcon(true, 14, 2, L"nether_wart_stage_0");
            this->addIcon(true, 14, 3, L"nether_wart_stage_1");
            this->addIcon(true, 14, 4, L"nether_wart_stage_2");
            this->addIcon(true, 14, 5, L"sandstone_carved");
            this->addIcon(true, 14, 6, L"sandstone_smooth");
            this->addIcon(true, 14, 7, L"anvil_top");
            this->addIcon(true, 14, 8, L"anvil_top_damaged_2");
            this->addIcon(true, 14, 9, L"quartz_block_chiseled");
            this->addIcon(true, 14, 10, L"quartz_block_lines");
            this->addIcon(true, 14, 11, L"quartz_block_side");
            this->addIcon(true, 14, 12, L"hopper_inside");
            this->addIcon(true, 14, 13, L"lava");
            this->addIconSize(true, 14, 14, L"lava_flow", 2, 2);
            this->addIcon(true, 15, 0, L"destroy_0");
            this->addIcon(true, 15, 1, L"destroy_1");
            this->addIcon(true, 15, 2, L"destroy_2");
            this->addIcon(true, 15, 3, L"destroy_3");
            this->addIcon(true, 15, 4, L"destroy_4");
            this->addIcon(true, 15, 5, L"destroy_5");
            this->addIcon(true, 15, 6, L"destroy_6");
            this->addIcon(true, 15, 7, L"destroy_7");
            this->addIcon(true, 15, 8, L"destroy_8");
            this->addIcon(true, 15, 9, L"destroy_9");
            this->addIcon(true, 15, 10, L"hay_block_side");
            this->addIcon(true, 15, 11, L"quartz_block_bottom");
            this->addIcon(true, 15, 12, L"hopper_top");
            this->addIcon(true, 15, 13, L"hay_block_top");
            this->addIcon(true, 16, 0, L"coal_block");
            this->addIcon(true, 16, 1, L"hardened_clay");
            this->addIcon(true, 16, 2, L"noteblock");
            this->addIcon(true, 16, 3, L"stone_andesite");
            this->addIcon(true, 16, 4, L"stone_andesite_smooth");
            this->addIcon(true, 16, 5, L"stone_diorite");
            this->addIcon(true, 16, 6, L"stone_diorite_smooth");
            this->addIcon(true, 16, 7, L"stone_granite");
            this->addIcon(true, 16, 8, L"stone_granite_smooth");
            this->addIcon(true, 16, 9, L"potatoes_stage_0");
            this->addIcon(true, 16, 10, L"potatoes_stage_1");
            this->addIcon(true, 16, 11, L"potatoes_stage_2");
            this->addIcon(true, 16, 12, L"potatoes_stage_3");
            this->addIcon(true, 16, 13, L"log_spruce_top");
            this->addIcon(true, 16, 14, L"log_jungle_top");
            this->addIcon(true, 16, 15, L"log_birch_top");
            this->addIcon(true, 17, 0, L"hardened_clay_stained_black");
            this->addIcon(true, 17, 1, L"hardened_clay_stained_blue");
            this->addIcon(true, 17, 2, L"hardened_clay_stained_brown");
            this->addIcon(true, 17, 3, L"hardened_clay_stained_cyan");
            this->addIcon(true, 17, 4, L"hardened_clay_stained_gray");
            this->addIcon(true, 17, 5, L"hardened_clay_stained_green");
            this->addIcon(true, 17, 6, L"hardened_clay_stained_light_blue");
            this->addIcon(true, 17, 7, L"hardened_clay_stained_lime");
            this->addIcon(true, 17, 8, L"hardened_clay_stained_magenta");
            this->addIcon(true, 17, 9, L"hardened_clay_stained_orange");
            this->addIcon(true, 17, 10, L"hardened_clay_stained_pink");
            this->addIcon(true, 17, 11, L"hardened_clay_stained_purple");
            this->addIcon(true, 17, 12, L"hardened_clay_stained_red");
            this->addIcon(true, 17, 13, L"hardened_clay_stained_silver");
            this->addIcon(true, 17, 14, L"hardened_clay_stained_white");
            this->addIcon(true, 17, 15, L"hardened_clay_stained_yellow");
            this->addIcon(true, 18, 0, L"glass_black");
            this->addIcon(true, 18, 1, L"glass_blue");
            this->addIcon(true, 18, 2, L"glass_brown");
            this->addIcon(true, 18, 3, L"glass_cyan");
            this->addIcon(true, 18, 4, L"glass_gray");
            this->addIcon(true, 18, 5, L"glass_green");
            this->addIcon(true, 18, 6, L"glass_light_blue");
            this->addIcon(true, 18, 7, L"glass_lime");
            this->addIcon(true, 18, 8, L"glass_magenta");
            this->addIcon(true, 18, 9, L"glass_orange");
            this->addIcon(true, 18, 10, L"glass_pink");
            this->addIcon(true, 18, 11, L"glass_purple");
            this->addIcon(true, 18, 12, L"glass_red");
            this->addIcon(true, 18, 13, L"glass_silver");
            this->addIcon(true, 18, 14, L"glass_white");
            this->addIcon(true, 18, 15, L"glass_yellow");
            this->addIcon(true, 19, 0, L"glass_pane_top_black");
            this->addIcon(true, 19, 1, L"glass_pane_top_blue");
            this->addIcon(true, 19, 2, L"glass_pane_top_brown");
            this->addIcon(true, 19, 3, L"glass_pane_top_cyan");
            this->addIcon(true, 19, 4, L"glass_pane_top_gray");
            this->addIcon(true, 19, 5, L"glass_pane_top_green");
            this->addIcon(true, 19, 6, L"glass_pane_top_light_blue");
            this->addIcon(true, 19, 7, L"glass_pane_top_lime");
            this->addIcon(true, 19, 8, L"glass_pane_top_magenta");
            this->addIcon(true, 19, 9, L"glass_pane_top_orange");
            this->addIcon(true, 19, 10, L"glass_pane_top_pink");
            this->addIcon(true, 19, 11, L"glass_pane_top_purple");
            this->addIcon(true, 19, 12, L"glass_pane_top_red");
            this->addIcon(true, 19, 13, L"glass_pane_top_silver");
            this->addIcon(true, 19, 14, L"glass_pane_top_white");
            this->addIcon(true, 19, 15, L"glass_pane_top_yellow");
            this->addIcon(true, 20, 0, L"double_plant_fern_top");
            this->addIcon(true, 20, 1, L"double_plant_grass_top");
            this->addIcon(true, 20, 2, L"double_plant_paeonia_top");
            this->addIcon(true, 20, 3, L"double_plant_rose_top");
            this->addIcon(true, 20, 4, L"double_plant_syringa_top");
            this->addIcon(true, 20, 5, L"flower_tulip_orange");
            this->addIcon(true, 20, 6, L"double_plant_sunflower_top");
            this->addIcon(true, 20, 7, L"double_plant_sunflower_front");
            this->addIcon(true, 20, 8, L"log_acacia");
            this->addIcon(true, 20, 9, L"log_acacia_top");
            this->addIcon(true, 20, 10, L"planks_acacia");
            this->addIcon(true, 20, 11, L"leaves_acacia");
            this->addIcon(true, 20, 12, L"leaves_acacia_fast");
            this->addIcon(true, 20, 13, L"prismarine_bricks");
            this->addIcon(true, 20, 14, L"red_sand");
            this->addIcon(true, 20, 15, L"red_sandstone_top");
            this->addIcon(true, 21, 0, L"double_plant_fern_bottom");
            this->addIcon(true, 21, 1, L"double_plant_grass_bottom");
            this->addIcon(true, 21, 2, L"double_plant_paeonia_bottom");
            this->addIcon(true, 21, 3, L"double_plant_rose_bottom");
            this->addIcon(true, 21, 4, L"double_plant_syringa_bottom");
            this->addIcon(true, 21, 5, L"flower_tulip_pink");
            this->addIcon(true, 21, 6, L"double_plant_sunflower_bottom");
            this->addIcon(true, 21, 7, L"double_plant_sunflower_back");
            this->addIcon(true, 21, 8, L"log_big_oak");
            this->addIcon(true, 21, 9, L"log_big_oak_top");
            this->addIcon(true, 21, 10, L"planks_big_oak");
            this->addIcon(true, 21, 11, L"leaves_big_oak");
            this->addIcon(true, 21, 12, L"leaves_big_oak_fast");
            this->addIcon(true, 21, 13, L"prismarine_dark");
            this->addIcon(true, 21, 14, L"red_sandstone_bottom");
            this->addIcon(true, 21, 15, L"red_sandstone_normal");
            this->addIcon(true, 22, 0, L"flower_alium");
            this->addIcon(true, 22, 1, L"flower_blue_orchid");
            this->addIcon(true, 22, 2, L"flower_houstonia");
            this->addIcon(true, 22, 3, L"flower_oxeye_daisy");
            this->addIcon(true, 22, 4, L"flower_tulip_red");
            this->addIcon(true, 22, 5, L"flower_tulip_white");
            this->addIcon(true, 22, 6, L"sapling_acacia");
            this->addIcon(true, 22, 7, L"sapling_roofed_oak");
            this->addIcon(true, 22, 8, L"coarse_dirt");
            this->addIcon(true, 22, 9, L"dirt_podzol_side");
            this->addIcon(true, 22, 10, L"dirt_podzol_top");
            this->addIcon(true, 22, 11, L"leaves_birch");
            this->addIcon(true, 22, 12, L"leaves_birch_fast");
            this->addIcon(true, 22, 13, L"prismarine_rough");
            this->addIcon(true, 22, 14, L"red_sandstone_carved");
            this->addIcon(true, 22, 15, L"red_sandstone_smooth");
            this->addIcon(true, 23, 0, L"door_acacia_upper");
            this->addIcon(true, 23, 1, L"door_birch_upper");
            this->addIcon(true, 23, 2, L"door_dark_oak_upper");
            this->addIcon(true, 23, 3, L"door_jungle_upper");
            this->addIcon(true, 23, 4, L"door_spruce_upper");
            this->addIcon(true, 23, 5, L"chorus_flower");
            this->addIcon(true, 23, 6, L"chorus_flower_dead");
            this->addIcon(true, 23, 7, L"chorus_flower_plant");
            this->addIcon(true, 23, 8, L"end_bricks");
            this->addIcon(true, 23, 9, L"grass_path_side");
            this->addIcon(true, 23, 10, L"grass_path_top");
            this->addIcon(true, 23, 11, L"barrier");
            this->addIcon(true, 23, 12, L"ice_packed");
            this->addIcon(true, 23, 13, L"sea_lantern");
            this->addIcon(true, 23, 14, L"daylight_detector_inverted_top");
            this->addIcon(true, 23, 15, L"iron_trapdoor");
            this->addIcon(true, 24, 0, L"door_acacia_lower");
            this->addIcon(true, 24, 1, L"door_birch_lower");
            this->addIcon(true, 24, 2, L"door_dark_oak_lower");
            this->addIcon(true, 24, 3, L"door_jungle_lower");
            this->addIcon(true, 24, 4, L"door_spruce_lower");
            this->addIcon(true, 24, 5, L"purpur_block");
            this->addIcon(true, 24, 6, L"purpur_pillar");
            this->addIcon(true, 24, 7, L"purpur_pillar_top");
            this->addIcon(true, 24, 8, L"end_rod");
            this->addIcon(true, 24, 9, L"magma");
            this->addIcon(true, 24, 10, L"nether_wart_block");
            this->addIcon(true, 24, 11, L"red_nether_brick");
            this->addIcon(true, 24, 12, L"frosted_ice_0");
            this->addIcon(true, 24, 13, L"frosted_ice_1");
            this->addIcon(true, 24, 14, L"frosted_ice_2");
            this->addIcon(true, 24, 15, L"frosted_ice_3");
            this->addIcon(true, 25, 0, L"beetroots_stage_0");
            this->addIcon(true, 25, 1, L"beetroots_stage_1");
            this->addIcon(true, 25, 2, L"beetroots_stage_2");
            this->addIcon(true, 25, 3, L"beetroots_stage_3");
            this->addIcon(true, 25, 4, L"chain_command_block_back");
            this->addIcon(true, 25, 5, L"chain_command_block_conditional");
            this->addIcon(true, 25, 6, L"chain_command_block_front");
            this->addIcon(true, 25, 7, L"chain_command_block_side");
            this->addIcon(true, 25, 8, L"command_block_back");
            this->addIcon(true, 25, 9, L"command_block_conditional");
            this->addIcon(true, 25, 10, L"command_block_front");
            this->addIcon(true, 25, 11, L"command_block_side");
            this->addIcon(true, 25, 12, L"repeating_command_block_back");
            this->addIcon(true, 25, 13, L"repeating_command_block_conditional");
            this->addIcon(true, 25, 14, L"repeating_command_block_front");
            this->addIcon(true, 25, 15, L"repeating_command_block_side");
            this->addIcon(true, 26, 0, L"bone_block_side");
            this->addIcon(true, 26, 1, L"bone_block_top");
            this->addIcon(true, 26, 2, L"unused");
            this->addIcon(true, 26, 3, L"unused");
            this->addIcon(true, 26, 4, L"observer_front");
            this->addIcon(true, 26, 5, L"observer_side");
            this->addIcon(true, 26, 6, L"observer_back");
            this->addIcon(true, 26, 7, L"observer_back_lit");
            this->addIcon(true, 26, 8, L"observer_top");
            this->addIcon(true, 26, 9, L"goldRing");
            this->addIcon(true, 26, 10, L"emeraldRing");
            this->addIcon(true, 26, 11, L"structure_block");
            this->addIcon(true, 26, 12, L"structure_block_corner");
            this->addIcon(true, 26, 13, L"structure_block_data");
            this->addIcon(true, 26, 14, L"structure_block_load");
            this->addIcon(true, 26, 15, L"structure_block_save");
            this->addIcon(true, 27, 0, L"concrete_black");
            this->addIcon(true, 27, 1, L"concrete_blue");
            this->addIcon(true, 27, 2, L"concrete_brown");
            this->addIcon(true, 27, 3, L"concrete_cyan");
            this->addIcon(true, 27, 4, L"concrete_gray");
            this->addIcon(true, 27, 5, L"concrete_green");
            this->addIcon(true, 27, 6, L"concrete_light_blue");
            this->addIcon(true, 27, 7, L"concrete_lime");
            this->addIcon(true, 27, 8, L"concrete_magenta");
            this->addIcon(true, 27, 9, L"concrete_orange");
            this->addIcon(true, 27, 10, L"concrete_pink");
            this->addIcon(true, 27, 11, L"concrete_purple");
            this->addIcon(true, 27, 12, L"concrete_red");
            this->addIcon(true, 27, 13, L"concrete_silver");
            this->addIcon(true, 27, 14, L"concrete_white");
            this->addIcon(true, 27, 15, L"concrete_yellow");
            this->addIcon(true, 28, 0, L"concrete_powder_black");
            this->addIcon(true, 28, 1, L"concrete_powder_blue");
            this->addIcon(true, 28, 2, L"concrete_powder_brown");
            this->addIcon(true, 28, 3, L"concrete_powder_cyan");
            this->addIcon(true, 28, 4, L"concrete_powder_gray");
            this->addIcon(true, 28, 5, L"concrete_powder_green");
            this->addIcon(true, 28, 6, L"concrete_powder_light_blue");
            this->addIcon(true, 28, 7, L"concrete_powder_lime");
            this->addIcon(true, 28, 8, L"concrete_powder_magenta");
            this->addIcon(true, 28, 9, L"concrete_powder_orange");
            this->addIcon(true, 28, 10, L"concrete_powder_pink");
            this->addIcon(true, 28, 11, L"concrete_powder_purple");
            this->addIcon(true, 28, 12, L"concrete_powder_red");
            this->addIcon(true, 28, 13, L"concrete_powder_silver");
            this->addIcon(true, 28, 14, L"concrete_powder_white");
            this->addIcon(true, 28, 15, L"concrete_powder_yellow");
            this->addIcon(true, 29, 0, L"glazed_terracotta_black");
            this->addIcon(true, 29, 1, L"glazed_terracotta_blue");
            this->addIcon(true, 29, 2, L"glazed_terracotta_brown");
            this->addIcon(true, 29, 3, L"glazed_terracotta_cyan");
            this->addIcon(true, 29, 4, L"glazed_terracotta_gray");
            this->addIcon(true, 29, 5, L"glazed_terracotta_green");
            this->addIcon(true, 29, 6, L"glazed_terracotta_light_blue");
            this->addIcon(true, 29, 7, L"glazed_terracotta_lime");
            this->addIcon(true, 29, 8, L"glazed_terracotta_magenta");
            this->addIcon(true, 29, 9, L"glazed_terracotta_orange");
            this->addIcon(true, 29, 10, L"glazed_terracotta_pink");
            this->addIcon(true, 29, 11, L"glazed_terracotta_purple");
            this->addIcon(true, 29, 12, L"glazed_terracotta_red");
            this->addIcon(true, 29, 13, L"glazed_terracotta_silver");
            this->addIcon(true, 29, 14, L"glazed_terracotta_white");
            this->addIcon(true, 29, 15, L"glazed_terracotta_yellow");
            this->addIcon(true, 30, 0, L"shulker_top");
            this->addIcon(true, 30, 2, L"cauldron_water");
        }
    }
}

Texture* TextureAtlas::getStitchedTexture() {
    return this->mStitchedTexture;
}