#include "CPlatformNetworkManager.h"
#include "INQRNetworkManagerListener.h"
#include "Nintendo/NX/Network/NQRNetworkManager_NX.h"

class CPlatformNetworkManagerNintendo : public CPlatformNetworkManager, protected INQRNetworkManagerListener {
public:
    class PlayerFlags {};

    static INetworkPlayer* getNetworkPlayer(NQRNetworkPlayer*);
    static int RemovePlayerOnSocketClosedThreadProc(void*);

    void TickSearch();
    void sub_71007C2578();

    void Initialise(CGameNetworkManager*, int) override;
    void Terminate() override;
    int GetJoiningReadyPercentage() override;
    int CorrectErrorIDS(int) override;
    void DoWork() override;
    int GetPlayerCount() override;
    int GetOnlinePlayerCount() override;
    int GetLocalPlayerMask(int) override;
    void AddLocalPlayerByUserIndex(int) override;
    void RemoveLocalPlayerByUserIndex(int) override;
    int AddLocalPlayerByPlayerUID(PlayerUID) override;
    INetworkPlayer* GetLocalPlayerByUserIndex(int) override;
    INetworkPlayer* GetPlayerByIndex(int) override;
    INetworkPlayer* GetPlayerByXuid(PlayerUID) override;
    INetworkPlayer* GetPlayerBySmallId(unsigned char) override;
    bool ShouldMessageForFullSession() override;
    INetworkPlayer* GetHostPlayer() override;
    bool IsHost() override;
    void JoinGameFromInviteInfo(int, int, const nn::friends::FriendPresence*) override;
    bool LeaveGame(bool) override;
    bool IsInSession() override;
    bool IsInGameplay() override;
    bool IsReadyToPlayOrIdle() override;
    bool IsInStatsEnabledSession() override;
    bool IsMatchmakingEnabled() override;
    bool IsHandlingBootInvite() override;
    bool SessionHasSpace(unsigned int) override;
    // bool SessionHasMii(int) override;
    void SendInviteGUI(int) override;
    bool IsAddingPlayer() override;
    void HostGame(int, bool, bool, unsigned char, EMiniGameId, unsigned int, unsigned int*) override;
    int JoinGame(FriendSessionInfo*, int, int, bool) override;
    bool FindAndJoinGame(int, int, EMiniGameId, unsigned int, unsigned int*, unsigned int*) override;
    void CancelJoinGame() override;
    bool SetLocalGame(bool) override;
    bool IsLocalGame() override;
    bool SetPrivateGame(bool) override;
    bool IsPrivateGame() override;
    bool IsLeavingGame() override;
    void ResetLeavingGame() override;
    void RegisterPlayerChangedCallback(int, void (*)(void*, INetworkPlayer*, bool), void*) override;
    void UnRegisterPlayerChangedCallback(int, void (*)(void*, INetworkPlayer*, bool), void*) override;
    void HandleSignInChange() override;
    void _RunNetworkGame() override;
    bool _LeaveGame(bool, bool) override;
    void _HostGame(int, unsigned char, EMiniGameId, unsigned int, unsigned int*) override;
    void _StartGame() override;
    void UpdateAndSetGameSessionData(INetworkPlayer*) override;
    void RemoveLocalPlayer(INetworkPlayer*) override;
    void SystemFlagAddPlayer(INetworkPlayer*) override;
    void SystemFlagSet(INetworkPlayer*, int) override;
    void SystemFlagGet(INetworkPlayer*, int) override;
    void SystemFlagClearAll(INetworkPlayer*) override;
    void GatherStats() override;
    void GatherRTTStats() override;
    void SetSessionTexturePackParentId(int) override;
    void SetSessionSubTexturePackId(int) override;
    void SetSessionGameModeId(int) override;
    void Notify(int, unsigned long) override;
    void GetSessionList(int, int, bool) override;
    void GetGameSessionInfo(int, unsigned int, FriendSessionInfo*) override;
    void SetSessionsUpdatedCallback(void (*)(void*), void*) override;
    void GetFullFriendSessionInfo(FriendSessionInfo*, void (*)(bool, void*), void*) override;
    void ForceFriendsSessionRefresh() override;
    void ClearFriendsSessions() override;
    void AlreadyInSession(const nn::friends::FriendPresence*) override;
    void GetAgeRestricted() override;
    void usingAdhocMode() override;
    void setAdhocMode(bool) override;
    void startAdhocMatching() override;
    bool isAdhocConnected() override;
    void connectToAdhoc() override;
    bool isAdhocModeChangeInProgress() override;
    void AttemptAdhocSignIn(int (*)(void*, bool, int), void*, bool) override;
    void setLanMode(bool) override;
    void usingLanMode() override;
    bool isLanConnected() override;
    bool isLanModeChangeInProgress() override;
    void checkValidInviteData(const nn::friends::FriendPresence*) override;
    void SetExitAndJoinFromInviteInProgress(bool) override;
    void CancelDisconnectFromExitAndJoin() override;
    void FakeLocalPlayerJoined() override;
    void GetDisplayNameByGamertag(std::wstring) override;
    void GetOutstandingAckCount(INetworkPlayer*) override;
    void TryToConnectOnline(int (*)(void*, bool, int), void*, bool) override;
    void AttemptPSNSignIn(int (*)(void*, bool, int), void*, bool, int) override;
    void RecvInviteGUI() override;
    void UpdateInviteData(void*) override;
    void CheckFriendsCanPlay(int, int&, std::shared_ptr<ClientboundPreLoginPacket>, int, int&, int&, int&,
                             int&) override;
    ~CPlatformNetworkManagerNintendo();

    char m_byte10;
    bool m_mRequestEnableAdhoc;
    bool m_mRequestDisableAdhoc;
    char m_mByte13;
    bool m_mRequestSignIn;
    bool m_mRequestSignout;
    void* m_qword18;
    void* m_qword20;
    NQRNetworkManager_NX* m_mNqrNetworkManager;
    void* m_qword30;
    std::vector<NQRNetworkPlayer*> m_mPlayers;
    bool m_mLeavingGame;
    bool m_mRequestLeaveRoom;
    char m_gap52;
    bool m_byte53;
    bool m_byte54;
    bool m_mLocalGame;
    bool m_mPrivateGame;
    int m_dword58;
    bool m_bool5C;
    char m_gap5C[387];
    void* m_qword1E0;  // 480
    void* m_qword1E8;
    void* m_qword1F0;
    void* m_qword1F8;
    void* m_qword200;
    void* m_qword208;
    void* m_qword210;
    void* m_qword218;
    void* m_qword220;
    std::vector<PlayerFlags*> m_mPlayerFlags;
    void* m_qword240;
    std::vector<FriendSessionInfo*> m_mFriendSessionInfos;
    void* m_qword260;
    void* m_qword268;
    char m_gap270[4];
    char m_byte274;
    void* m_qword278;
    void* m_qword280;
    void* m_qword288;
    std::vector<INetworkPlayer*> m_mNetworkPlayers;
};